//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaixaBancosClient.CaixaBancosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinFechamentoCaixaBancoDTO", Namespace="http://schemas.datacontract.org/2004/07/CaixaBancosService.Model")]
    [System.SerializableAttribute()]
    public partial class FinFechamentoCaixaBancoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ChequeNaoCompensadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataFechamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdContaCaixaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesAnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PagamentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RecebimentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SaldoAnteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SaldoContaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SaldoDisponivelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ano {
            get {
                return this.AnoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnoField, value) != true)) {
                    this.AnoField = value;
                    this.RaisePropertyChanged("Ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ChequeNaoCompensado {
            get {
                return this.ChequeNaoCompensadoField;
            }
            set {
                if ((this.ChequeNaoCompensadoField.Equals(value) != true)) {
                    this.ChequeNaoCompensadoField = value;
                    this.RaisePropertyChanged("ChequeNaoCompensado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataFechamento {
            get {
                return this.DataFechamentoField;
            }
            set {
                if ((this.DataFechamentoField.Equals(value) != true)) {
                    this.DataFechamentoField = value;
                    this.RaisePropertyChanged("DataFechamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdContaCaixa {
            get {
                return this.IdContaCaixaField;
            }
            set {
                if ((this.IdContaCaixaField.Equals(value) != true)) {
                    this.IdContaCaixaField = value;
                    this.RaisePropertyChanged("IdContaCaixa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mes {
            get {
                return this.MesField;
            }
            set {
                if ((object.ReferenceEquals(this.MesField, value) != true)) {
                    this.MesField = value;
                    this.RaisePropertyChanged("Mes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MesAno {
            get {
                return this.MesAnoField;
            }
            set {
                if ((object.ReferenceEquals(this.MesAnoField, value) != true)) {
                    this.MesAnoField = value;
                    this.RaisePropertyChanged("MesAno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Pagamentos {
            get {
                return this.PagamentosField;
            }
            set {
                if ((this.PagamentosField.Equals(value) != true)) {
                    this.PagamentosField = value;
                    this.RaisePropertyChanged("Pagamentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Recebimentos {
            get {
                return this.RecebimentosField;
            }
            set {
                if ((this.RecebimentosField.Equals(value) != true)) {
                    this.RecebimentosField = value;
                    this.RaisePropertyChanged("Recebimentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SaldoAnterior {
            get {
                return this.SaldoAnteriorField;
            }
            set {
                if ((this.SaldoAnteriorField.Equals(value) != true)) {
                    this.SaldoAnteriorField = value;
                    this.RaisePropertyChanged("SaldoAnterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SaldoConta {
            get {
                return this.SaldoContaField;
            }
            set {
                if ((this.SaldoContaField.Equals(value) != true)) {
                    this.SaldoContaField = value;
                    this.RaisePropertyChanged("SaldoConta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SaldoDisponivel {
            get {
                return this.SaldoDisponivelField;
            }
            set {
                if ((this.SaldoDisponivelField.Equals(value) != true)) {
                    this.SaldoDisponivelField = value;
                    this.RaisePropertyChanged("SaldoDisponivel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewFinChequeNaoCompensadoDTO", Namespace="http://schemas.datacontract.org/2004/07/CaixaBancosService.Model")]
    [System.SerializableAttribute()]
    public partial class ViewFinChequeNaoCompensadoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdContaCaixaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeContaCaixaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroChequeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroTalaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusChequeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TalaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataStatus {
            get {
                return this.DataStatusField;
            }
            set {
                if ((this.DataStatusField.Equals(value) != true)) {
                    this.DataStatusField = value;
                    this.RaisePropertyChanged("DataStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdContaCaixa {
            get {
                return this.IdContaCaixaField;
            }
            set {
                if ((this.IdContaCaixaField.Equals(value) != true)) {
                    this.IdContaCaixaField = value;
                    this.RaisePropertyChanged("IdContaCaixa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeContaCaixa {
            get {
                return this.NomeContaCaixaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeContaCaixaField, value) != true)) {
                    this.NomeContaCaixaField = value;
                    this.RaisePropertyChanged("NomeContaCaixa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroCheque {
            get {
                return this.NumeroChequeField;
            }
            set {
                if ((this.NumeroChequeField.Equals(value) != true)) {
                    this.NumeroChequeField = value;
                    this.RaisePropertyChanged("NumeroCheque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroTalao {
            get {
                return this.NumeroTalaoField;
            }
            set {
                if ((this.NumeroTalaoField.Equals(value) != true)) {
                    this.NumeroTalaoField = value;
                    this.RaisePropertyChanged("NumeroTalao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCheque {
            get {
                return this.StatusChequeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusChequeField, value) != true)) {
                    this.StatusChequeField = value;
                    this.RaisePropertyChanged("StatusCheque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Talao {
            get {
                return this.TalaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TalaoField, value) != true)) {
                    this.TalaoField = value;
                    this.RaisePropertyChanged("Talao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewFinMovimentoCaixaBancoDTO", Namespace="http://schemas.datacontract.org/2004/07/CaixaBancosService.Model")]
    [System.SerializableAttribute()]
    public partial class ViewFinMovimentoCaixaBancoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataLancamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataPagoRecebidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoDocumentoOrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HistoricoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdContaCaixaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeContaCaixaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomePessoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataLancamento {
            get {
                return this.DataLancamentoField;
            }
            set {
                if ((this.DataLancamentoField.Equals(value) != true)) {
                    this.DataLancamentoField = value;
                    this.RaisePropertyChanged("DataLancamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataPagoRecebido {
            get {
                return this.DataPagoRecebidoField;
            }
            set {
                if ((this.DataPagoRecebidoField.Equals(value) != true)) {
                    this.DataPagoRecebidoField = value;
                    this.RaisePropertyChanged("DataPagoRecebido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoDocumentoOrigem {
            get {
                return this.DescricaoDocumentoOrigemField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoDocumentoOrigemField, value) != true)) {
                    this.DescricaoDocumentoOrigemField = value;
                    this.RaisePropertyChanged("DescricaoDocumentoOrigem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Historico {
            get {
                return this.HistoricoField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoricoField, value) != true)) {
                    this.HistoricoField = value;
                    this.RaisePropertyChanged("Historico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdContaCaixa {
            get {
                return this.IdContaCaixaField;
            }
            set {
                if ((this.IdContaCaixaField.Equals(value) != true)) {
                    this.IdContaCaixaField = value;
                    this.RaisePropertyChanged("IdContaCaixa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeContaCaixa {
            get {
                return this.NomeContaCaixaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeContaCaixaField, value) != true)) {
                    this.NomeContaCaixaField = value;
                    this.RaisePropertyChanged("NomeContaCaixa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomePessoa {
            get {
                return this.NomePessoaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomePessoaField, value) != true)) {
                    this.NomePessoaField = value;
                    this.RaisePropertyChanged("NomePessoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operacao {
            get {
                return this.OperacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacaoField, value) != true)) {
                    this.OperacaoField = value;
                    this.RaisePropertyChanged("Operacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContabilContaDTO", Namespace="http://schemas.datacontract.org/2004/07/CaixaBancosService.Model")]
    [System.SerializableAttribute()]
    public partial class ContabilContaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassificacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoEfdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoReduzidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CaixaBancosClient.CaixaBancosService.ContabilContaDTO ContabilContaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInclusaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DfcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LivroCaixaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaturezaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatrimonioResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classificacao {
            get {
                return this.ClassificacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassificacaoField, value) != true)) {
                    this.ClassificacaoField = value;
                    this.RaisePropertyChanged("Classificacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoEfd {
            get {
                return this.CodigoEfdField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoEfdField, value) != true)) {
                    this.CodigoEfdField = value;
                    this.RaisePropertyChanged("CodigoEfd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoReduzido {
            get {
                return this.CodigoReduzidoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoReduzidoField, value) != true)) {
                    this.CodigoReduzidoField = value;
                    this.RaisePropertyChanged("CodigoReduzido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CaixaBancosClient.CaixaBancosService.ContabilContaDTO ContabilConta {
            get {
                return this.ContabilContaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContabilContaField, value) != true)) {
                    this.ContabilContaField = value;
                    this.RaisePropertyChanged("ContabilConta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInclusao {
            get {
                return this.DataInclusaoField;
            }
            set {
                if ((this.DataInclusaoField.Equals(value) != true)) {
                    this.DataInclusaoField = value;
                    this.RaisePropertyChanged("DataInclusao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dfc {
            get {
                return this.DfcField;
            }
            set {
                if ((object.ReferenceEquals(this.DfcField, value) != true)) {
                    this.DfcField = value;
                    this.RaisePropertyChanged("Dfc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LivroCaixa {
            get {
                return this.LivroCaixaField;
            }
            set {
                if ((object.ReferenceEquals(this.LivroCaixaField, value) != true)) {
                    this.LivroCaixaField = value;
                    this.RaisePropertyChanged("LivroCaixa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Natureza {
            get {
                return this.NaturezaField;
            }
            set {
                if ((object.ReferenceEquals(this.NaturezaField, value) != true)) {
                    this.NaturezaField = value;
                    this.RaisePropertyChanged("Natureza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ordem {
            get {
                return this.OrdemField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdemField, value) != true)) {
                    this.OrdemField = value;
                    this.RaisePropertyChanged("Ordem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatrimonioResultado {
            get {
                return this.PatrimonioResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.PatrimonioResultadoField, value) != true)) {
                    this.PatrimonioResultadoField = value;
                    this.RaisePropertyChanged("PatrimonioResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacaoField, value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDTO", Namespace="http://schemas.datacontract.org/2004/07/CaixaBancosService.Model")]
    [System.SerializableAttribute()]
    public partial class UsuarioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdColaboradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPapelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Administrador {
            get {
                return this.AdministradorField;
            }
            set {
                if ((object.ReferenceEquals(this.AdministradorField, value) != true)) {
                    this.AdministradorField = value;
                    this.RaisePropertyChanged("Administrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdColaborador {
            get {
                return this.IdColaboradorField;
            }
            set {
                if ((this.IdColaboradorField.Equals(value) != true)) {
                    this.IdColaboradorField = value;
                    this.RaisePropertyChanged("IdColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPapel {
            get {
                return this.IdPapelField;
            }
            set {
                if ((this.IdPapelField.Equals(value) != true)) {
                    this.IdPapelField = value;
                    this.RaisePropertyChanged("IdPapel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewControleAcessoDTO", Namespace="http://schemas.datacontract.org/2004/07/CaixaBancosService.Model")]
    [System.SerializableAttribute()]
    public partial class ViewControleAcessoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormularioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPapelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formulario {
            get {
                return this.FormularioField;
            }
            set {
                if ((object.ReferenceEquals(this.FormularioField, value) != true)) {
                    this.FormularioField = value;
                    this.RaisePropertyChanged("Formulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((object.ReferenceEquals(this.HabilitadoField, value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncao {
            get {
                return this.IdFuncaoField;
            }
            set {
                if ((this.IdFuncaoField.Equals(value) != true)) {
                    this.IdFuncaoField = value;
                    this.RaisePropertyChanged("IdFuncao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPapel {
            get {
                return this.IdPapelField;
            }
            set {
                if ((this.IdPapelField.Equals(value) != true)) {
                    this.IdPapelField = value;
                    this.RaisePropertyChanged("IdPapel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContaCaixaDTO", Namespace="http://schemas.datacontract.org/2004/07/CaixaBancosService.Model")]
    [System.SerializableAttribute()]
    public partial class ContaCaixaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CaixaBancosClient.CaixaBancosService.ContabilContaDTO ContabilContaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DigitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CaixaBancosClient.CaixaBancosService.EmpresaDTO EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CaixaBancosClient.CaixaBancosService.ContabilContaDTO ContabilConta {
            get {
                return this.ContabilContaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContabilContaField, value) != true)) {
                    this.ContabilContaField = value;
                    this.RaisePropertyChanged("ContabilConta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Digito {
            get {
                return this.DigitoField;
            }
            set {
                if ((object.ReferenceEquals(this.DigitoField, value) != true)) {
                    this.DigitoField = value;
                    this.RaisePropertyChanged("Digito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CaixaBancosClient.CaixaBancosService.EmpresaDTO Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaDTO", Namespace="http://schemas.datacontract.org/2004/07/CaixaBancosService.Model")]
    [System.SerializableAttribute()]
    public partial class EmpresaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliquotaCofinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliquotaPisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliquotaSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnpjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoGpsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoIbgeCidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoIbgeUfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTerceirosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInicioAtividadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInscJuntaComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagemLogotipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoEstadualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoEstadualStField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoJuntaComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoMunicipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeFantasiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazaoSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuframaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoRegimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliquotaCofins {
            get {
                return this.AliquotaCofinsField;
            }
            set {
                if ((object.ReferenceEquals(this.AliquotaCofinsField, value) != true)) {
                    this.AliquotaCofinsField = value;
                    this.RaisePropertyChanged("AliquotaCofins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliquotaPis {
            get {
                return this.AliquotaPisField;
            }
            set {
                if ((object.ReferenceEquals(this.AliquotaPisField, value) != true)) {
                    this.AliquotaPisField = value;
                    this.RaisePropertyChanged("AliquotaPis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliquotaSat {
            get {
                return this.AliquotaSatField;
            }
            set {
                if ((object.ReferenceEquals(this.AliquotaSatField, value) != true)) {
                    this.AliquotaSatField = value;
                    this.RaisePropertyChanged("AliquotaSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cnpj {
            get {
                return this.CnpjField;
            }
            set {
                if ((object.ReferenceEquals(this.CnpjField, value) != true)) {
                    this.CnpjField = value;
                    this.RaisePropertyChanged("Cnpj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoGps {
            get {
                return this.CodigoGpsField;
            }
            set {
                if ((this.CodigoGpsField.Equals(value) != true)) {
                    this.CodigoGpsField = value;
                    this.RaisePropertyChanged("CodigoGps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoIbgeCidade {
            get {
                return this.CodigoIbgeCidadeField;
            }
            set {
                if ((this.CodigoIbgeCidadeField.Equals(value) != true)) {
                    this.CodigoIbgeCidadeField = value;
                    this.RaisePropertyChanged("CodigoIbgeCidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoIbgeUf {
            get {
                return this.CodigoIbgeUfField;
            }
            set {
                if ((this.CodigoIbgeUfField.Equals(value) != true)) {
                    this.CodigoIbgeUfField = value;
                    this.RaisePropertyChanged("CodigoIbgeUf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTerceiros {
            get {
                return this.CodigoTerceirosField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTerceirosField, value) != true)) {
                    this.CodigoTerceirosField = value;
                    this.RaisePropertyChanged("CodigoTerceiros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contato {
            get {
                return this.ContatoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContatoField, value) != true)) {
                    this.ContatoField = value;
                    this.RaisePropertyChanged("Contato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Crt {
            get {
                return this.CrtField;
            }
            set {
                if ((object.ReferenceEquals(this.CrtField, value) != true)) {
                    this.CrtField = value;
                    this.RaisePropertyChanged("Crt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInicioAtividades {
            get {
                return this.DataInicioAtividadesField;
            }
            set {
                if ((this.DataInicioAtividadesField.Equals(value) != true)) {
                    this.DataInicioAtividadesField = value;
                    this.RaisePropertyChanged("DataInicioAtividades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInscJuntaComercial {
            get {
                return this.DataInscJuntaComercialField;
            }
            set {
                if ((this.DataInscJuntaComercialField.Equals(value) != true)) {
                    this.DataInscJuntaComercialField = value;
                    this.RaisePropertyChanged("DataInscJuntaComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagemLogotipo {
            get {
                return this.ImagemLogotipoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemLogotipoField, value) != true)) {
                    this.ImagemLogotipoField = value;
                    this.RaisePropertyChanged("ImagemLogotipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoEstadual {
            get {
                return this.InscricaoEstadualField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoEstadualField, value) != true)) {
                    this.InscricaoEstadualField = value;
                    this.RaisePropertyChanged("InscricaoEstadual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoEstadualSt {
            get {
                return this.InscricaoEstadualStField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoEstadualStField, value) != true)) {
                    this.InscricaoEstadualStField = value;
                    this.RaisePropertyChanged("InscricaoEstadualSt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoJuntaComercial {
            get {
                return this.InscricaoJuntaComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoJuntaComercialField, value) != true)) {
                    this.InscricaoJuntaComercialField = value;
                    this.RaisePropertyChanged("InscricaoJuntaComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoMunicipal {
            get {
                return this.InscricaoMunicipalField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoMunicipalField, value) != true)) {
                    this.InscricaoMunicipalField = value;
                    this.RaisePropertyChanged("InscricaoMunicipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeFantasia {
            get {
                return this.NomeFantasiaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeFantasiaField, value) != true)) {
                    this.NomeFantasiaField = value;
                    this.RaisePropertyChanged("NomeFantasia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazaoSocial {
            get {
                return this.RazaoSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazaoSocialField, value) != true)) {
                    this.RazaoSocialField = value;
                    this.RaisePropertyChanged("RazaoSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suframa {
            get {
                return this.SuframaField;
            }
            set {
                if ((object.ReferenceEquals(this.SuframaField, value) != true)) {
                    this.SuframaField = value;
                    this.RaisePropertyChanged("Suframa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoRegime {
            get {
                return this.TipoRegimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoRegimeField, value) != true)) {
                    this.TipoRegimeField = value;
                    this.RaisePropertyChanged("TipoRegime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CaixaBancosService.ICaixaBancosService")]
    public interface ICaixaBancosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/deleteFinFechamentoCaixaBanco", ReplyAction="http://tempuri.org/ICaixaBancosService/deleteFinFechamentoCaixaBancoResponse")]
        int deleteFinFechamentoCaixaBanco(CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO finFechamentoCaixaBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/salvarAtualizarFinFechamentoCaixaBanco", ReplyAction="http://tempuri.org/ICaixaBancosService/salvarAtualizarFinFechamentoCaixaBancoResp" +
            "onse")]
        CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO salvarAtualizarFinFechamentoCaixaBanco(CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO finFechamentoCaixaBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectFinFechamentoCaixaBanco", ReplyAction="http://tempuri.org/ICaixaBancosService/selectFinFechamentoCaixaBancoResponse")]
        CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO selectFinFechamentoCaixaBanco(CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO finFechamentoCaixaBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectFinFechamentoCaixaBancoPagina", ReplyAction="http://tempuri.org/ICaixaBancosService/selectFinFechamentoCaixaBancoPaginaRespons" +
            "e")]
        System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO> selectFinFechamentoCaixaBancoPagina(int primeiroResultado, int quantidadeResultados, CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO finFechamentoCaixaBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/deleteViewFinChequeNaoCompensado", ReplyAction="http://tempuri.org/ICaixaBancosService/deleteViewFinChequeNaoCompensadoResponse")]
        int deleteViewFinChequeNaoCompensado(CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO viewFinChequeNaoCompensado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/salvarAtualizarViewFinChequeNaoCompensado", ReplyAction="http://tempuri.org/ICaixaBancosService/salvarAtualizarViewFinChequeNaoCompensadoR" +
            "esponse")]
        CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO salvarAtualizarViewFinChequeNaoCompensado(CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO viewFinChequeNaoCompensado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectViewFinChequeNaoCompensado", ReplyAction="http://tempuri.org/ICaixaBancosService/selectViewFinChequeNaoCompensadoResponse")]
        System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO> selectViewFinChequeNaoCompensado(CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO viewFinChequeNaoCompensado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectViewFinChequeNaoCompensadoPagina", ReplyAction="http://tempuri.org/ICaixaBancosService/selectViewFinChequeNaoCompensadoPaginaResp" +
            "onse")]
        System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO> selectViewFinChequeNaoCompensadoPagina(int primeiroResultado, int quantidadeResultados, CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO viewFinChequeNaoCompensado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectViewFinMovimentoCaixaBanco", ReplyAction="http://tempuri.org/ICaixaBancosService/selectViewFinMovimentoCaixaBancoResponse")]
        System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ViewFinMovimentoCaixaBancoDTO> selectViewFinMovimentoCaixaBanco(CaixaBancosClient.CaixaBancosService.ViewFinMovimentoCaixaBancoDTO viewFinMovimentoCaixaBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectViewFinMovimentoCaixaBancoPagina", ReplyAction="http://tempuri.org/ICaixaBancosService/selectViewFinMovimentoCaixaBancoPaginaResp" +
            "onse")]
        System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ViewFinMovimentoCaixaBancoDTO> selectViewFinMovimentoCaixaBancoPagina(int primeiroResultado, int quantidadeResultados, CaixaBancosClient.CaixaBancosService.ViewFinMovimentoCaixaBancoDTO viewFinMovimentoCaixaBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectPeriodoMovimentoCaixaBanco", ReplyAction="http://tempuri.org/ICaixaBancosService/selectPeriodoMovimentoCaixaBancoResponse")]
        System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ViewFinMovimentoCaixaBancoDTO> selectPeriodoMovimentoCaixaBanco(CaixaBancosClient.CaixaBancosService.ViewFinMovimentoCaixaBancoDTO movimentoCaixaBanco);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectContabilConta", ReplyAction="http://tempuri.org/ICaixaBancosService/selectContabilContaResponse")]
        System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ContabilContaDTO> selectContabilConta(CaixaBancosClient.CaixaBancosService.ContabilContaDTO contabilConta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectContabilContaPagina", ReplyAction="http://tempuri.org/ICaixaBancosService/selectContabilContaPaginaResponse")]
        System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ContabilContaDTO> selectContabilContaPagina(int primeiroResultado, int quantidadeResultados, CaixaBancosClient.CaixaBancosService.ContabilContaDTO contabilConta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectUsuario", ReplyAction="http://tempuri.org/ICaixaBancosService/selectUsuarioResponse")]
        CaixaBancosClient.CaixaBancosService.UsuarioDTO selectUsuario(string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectControleAcesso", ReplyAction="http://tempuri.org/ICaixaBancosService/selectControleAcessoResponse")]
        System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ViewControleAcessoDTO> selectControleAcesso(CaixaBancosClient.CaixaBancosService.ViewControleAcessoDTO viewControleAcesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectContaCaixa", ReplyAction="http://tempuri.org/ICaixaBancosService/selectContaCaixaResponse")]
        System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ContaCaixaDTO> selectContaCaixa(CaixaBancosClient.CaixaBancosService.ContaCaixaDTO contaCaixa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaixaBancosService/selectContaCaixaPagina", ReplyAction="http://tempuri.org/ICaixaBancosService/selectContaCaixaPaginaResponse")]
        System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ContaCaixaDTO> selectContaCaixaPagina(int primeiroResultado, int quantidadeResultados, CaixaBancosClient.CaixaBancosService.ContaCaixaDTO contaCaixa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICaixaBancosServiceChannel : CaixaBancosClient.CaixaBancosService.ICaixaBancosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CaixaBancosServiceClient : System.ServiceModel.ClientBase<CaixaBancosClient.CaixaBancosService.ICaixaBancosService>, CaixaBancosClient.CaixaBancosService.ICaixaBancosService {
        
        public CaixaBancosServiceClient() {
        }
        
        public CaixaBancosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CaixaBancosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaixaBancosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaixaBancosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int deleteFinFechamentoCaixaBanco(CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO finFechamentoCaixaBanco) {
            return base.Channel.deleteFinFechamentoCaixaBanco(finFechamentoCaixaBanco);
        }
        
        public CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO salvarAtualizarFinFechamentoCaixaBanco(CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO finFechamentoCaixaBanco) {
            return base.Channel.salvarAtualizarFinFechamentoCaixaBanco(finFechamentoCaixaBanco);
        }
        
        public CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO selectFinFechamentoCaixaBanco(CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO finFechamentoCaixaBanco) {
            return base.Channel.selectFinFechamentoCaixaBanco(finFechamentoCaixaBanco);
        }
        
        public System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO> selectFinFechamentoCaixaBancoPagina(int primeiroResultado, int quantidadeResultados, CaixaBancosClient.CaixaBancosService.FinFechamentoCaixaBancoDTO finFechamentoCaixaBanco) {
            return base.Channel.selectFinFechamentoCaixaBancoPagina(primeiroResultado, quantidadeResultados, finFechamentoCaixaBanco);
        }
        
        public int deleteViewFinChequeNaoCompensado(CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO viewFinChequeNaoCompensado) {
            return base.Channel.deleteViewFinChequeNaoCompensado(viewFinChequeNaoCompensado);
        }
        
        public CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO salvarAtualizarViewFinChequeNaoCompensado(CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO viewFinChequeNaoCompensado) {
            return base.Channel.salvarAtualizarViewFinChequeNaoCompensado(viewFinChequeNaoCompensado);
        }
        
        public System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO> selectViewFinChequeNaoCompensado(CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO viewFinChequeNaoCompensado) {
            return base.Channel.selectViewFinChequeNaoCompensado(viewFinChequeNaoCompensado);
        }
        
        public System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO> selectViewFinChequeNaoCompensadoPagina(int primeiroResultado, int quantidadeResultados, CaixaBancosClient.CaixaBancosService.ViewFinChequeNaoCompensadoDTO viewFinChequeNaoCompensado) {
            return base.Channel.selectViewFinChequeNaoCompensadoPagina(primeiroResultado, quantidadeResultados, viewFinChequeNaoCompensado);
        }
        
        public System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ViewFinMovimentoCaixaBancoDTO> selectViewFinMovimentoCaixaBanco(CaixaBancosClient.CaixaBancosService.ViewFinMovimentoCaixaBancoDTO viewFinMovimentoCaixaBanco) {
            return base.Channel.selectViewFinMovimentoCaixaBanco(viewFinMovimentoCaixaBanco);
        }
        
        public System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ViewFinMovimentoCaixaBancoDTO> selectViewFinMovimentoCaixaBancoPagina(int primeiroResultado, int quantidadeResultados, CaixaBancosClient.CaixaBancosService.ViewFinMovimentoCaixaBancoDTO viewFinMovimentoCaixaBanco) {
            return base.Channel.selectViewFinMovimentoCaixaBancoPagina(primeiroResultado, quantidadeResultados, viewFinMovimentoCaixaBanco);
        }
        
        public System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ViewFinMovimentoCaixaBancoDTO> selectPeriodoMovimentoCaixaBanco(CaixaBancosClient.CaixaBancosService.ViewFinMovimentoCaixaBancoDTO movimentoCaixaBanco) {
            return base.Channel.selectPeriodoMovimentoCaixaBanco(movimentoCaixaBanco);
        }
        
        public System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ContabilContaDTO> selectContabilConta(CaixaBancosClient.CaixaBancosService.ContabilContaDTO contabilConta) {
            return base.Channel.selectContabilConta(contabilConta);
        }
        
        public System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ContabilContaDTO> selectContabilContaPagina(int primeiroResultado, int quantidadeResultados, CaixaBancosClient.CaixaBancosService.ContabilContaDTO contabilConta) {
            return base.Channel.selectContabilContaPagina(primeiroResultado, quantidadeResultados, contabilConta);
        }
        
        public CaixaBancosClient.CaixaBancosService.UsuarioDTO selectUsuario(string login, string senha) {
            return base.Channel.selectUsuario(login, senha);
        }
        
        public System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ViewControleAcessoDTO> selectControleAcesso(CaixaBancosClient.CaixaBancosService.ViewControleAcessoDTO viewControleAcesso) {
            return base.Channel.selectControleAcesso(viewControleAcesso);
        }
        
        public System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ContaCaixaDTO> selectContaCaixa(CaixaBancosClient.CaixaBancosService.ContaCaixaDTO contaCaixa) {
            return base.Channel.selectContaCaixa(contaCaixa);
        }
        
        public System.Collections.Generic.List<CaixaBancosClient.CaixaBancosService.ContaCaixaDTO> selectContaCaixaPagina(int primeiroResultado, int quantidadeResultados, CaixaBancosClient.CaixaBancosService.ContaCaixaDTO contaCaixa) {
            return base.Channel.selectContaCaixaPagina(primeiroResultado, quantidadeResultados, contaCaixa);
        }
    }
}
