//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoClient.OrcamentoReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrcamentoPeriodoDTO", Namespace="http://schemas.datacontract.org/2004/07/OrcamentoService.Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class OrcamentoPeriodoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string periodoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string periodo {
            get {
                return this.periodoField;
            }
            set {
                if ((object.ReferenceEquals(this.periodoField, value) != true)) {
                    this.periodoField = value;
                    this.RaisePropertyChanged("periodo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NaturezaFinanceiraDTO", Namespace="http://schemas.datacontract.org/2004/07/OrcamentoService.Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class NaturezaFinanceiraDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classificacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPlanoNaturezaFinanceiraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string classificacao {
            get {
                return this.classificacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.classificacaoField, value) != true)) {
                    this.classificacaoField = value;
                    this.RaisePropertyChanged("classificacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlanoNaturezaFinanceira {
            get {
                return this.idPlanoNaturezaFinanceiraField;
            }
            set {
                if ((this.idPlanoNaturezaFinanceiraField.Equals(value) != true)) {
                    this.idPlanoNaturezaFinanceiraField = value;
                    this.RaisePropertyChanged("idPlanoNaturezaFinanceira");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParcelaPagarDTO", Namespace="http://schemas.datacontract.org/2004/07/OrcamentoService.Model")]
    [System.SerializableAttribute()]
    public partial class ParcelaPagarDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataEmissaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataVencimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> descontoAteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idStatusParcelaPagarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OrcamentoClient.OrcamentoReference.LancamentoPagarDTO lancamentoPagarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numeroParcelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<char> sofreRetencaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> taxaDescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> taxaJuroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> taxaMultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorDescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorJuroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorMultaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                if ((this.dataEmissaoField.Equals(value) != true)) {
                    this.dataEmissaoField = value;
                    this.RaisePropertyChanged("dataEmissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataVencimento {
            get {
                return this.dataVencimentoField;
            }
            set {
                if ((this.dataVencimentoField.Equals(value) != true)) {
                    this.dataVencimentoField = value;
                    this.RaisePropertyChanged("dataVencimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> descontoAte {
            get {
                return this.descontoAteField;
            }
            set {
                if ((this.descontoAteField.Equals(value) != true)) {
                    this.descontoAteField = value;
                    this.RaisePropertyChanged("descontoAte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idStatusParcelaPagar {
            get {
                return this.idStatusParcelaPagarField;
            }
            set {
                if ((this.idStatusParcelaPagarField.Equals(value) != true)) {
                    this.idStatusParcelaPagarField = value;
                    this.RaisePropertyChanged("idStatusParcelaPagar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrcamentoClient.OrcamentoReference.LancamentoPagarDTO lancamentoPagar {
            get {
                return this.lancamentoPagarField;
            }
            set {
                if ((object.ReferenceEquals(this.lancamentoPagarField, value) != true)) {
                    this.lancamentoPagarField = value;
                    this.RaisePropertyChanged("lancamentoPagar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numeroParcela {
            get {
                return this.numeroParcelaField;
            }
            set {
                if ((this.numeroParcelaField.Equals(value) != true)) {
                    this.numeroParcelaField = value;
                    this.RaisePropertyChanged("numeroParcela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<char> sofreRetencao {
            get {
                return this.sofreRetencaoField;
            }
            set {
                if ((this.sofreRetencaoField.Equals(value) != true)) {
                    this.sofreRetencaoField = value;
                    this.RaisePropertyChanged("sofreRetencao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> taxaDesconto {
            get {
                return this.taxaDescontoField;
            }
            set {
                if ((this.taxaDescontoField.Equals(value) != true)) {
                    this.taxaDescontoField = value;
                    this.RaisePropertyChanged("taxaDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> taxaJuro {
            get {
                return this.taxaJuroField;
            }
            set {
                if ((this.taxaJuroField.Equals(value) != true)) {
                    this.taxaJuroField = value;
                    this.RaisePropertyChanged("taxaJuro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> taxaMulta {
            get {
                return this.taxaMultaField;
            }
            set {
                if ((this.taxaMultaField.Equals(value) != true)) {
                    this.taxaMultaField = value;
                    this.RaisePropertyChanged("taxaMulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valor {
            get {
                return this.valorField;
            }
            set {
                if ((this.valorField.Equals(value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorDesconto {
            get {
                return this.valorDescontoField;
            }
            set {
                if ((this.valorDescontoField.Equals(value) != true)) {
                    this.valorDescontoField = value;
                    this.RaisePropertyChanged("valorDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorJuro {
            get {
                return this.valorJuroField;
            }
            set {
                if ((this.valorJuroField.Equals(value) != true)) {
                    this.valorJuroField = value;
                    this.RaisePropertyChanged("valorJuro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorMulta {
            get {
                return this.valorMultaField;
            }
            set {
                if ((this.valorMultaField.Equals(value) != true)) {
                    this.valorMultaField = value;
                    this.RaisePropertyChanged("valorMulta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LancamentoPagarDTO", Namespace="http://schemas.datacontract.org/2004/07/OrcamentoService.Model")]
    [System.SerializableAttribute()]
    public partial class LancamentoPagarDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataLancamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OrcamentoClient.OrcamentoReference.DocumentoOrigemDTO documentoOrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idFornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imagemDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<char> pagamentoCompartilhadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> primeiroVencimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantidadeParcelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorPagarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataLancamento {
            get {
                return this.dataLancamentoField;
            }
            set {
                if ((this.dataLancamentoField.Equals(value) != true)) {
                    this.dataLancamentoField = value;
                    this.RaisePropertyChanged("dataLancamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrcamentoClient.OrcamentoReference.DocumentoOrigemDTO documentoOrigem {
            get {
                return this.documentoOrigemField;
            }
            set {
                if ((object.ReferenceEquals(this.documentoOrigemField, value) != true)) {
                    this.documentoOrigemField = value;
                    this.RaisePropertyChanged("documentoOrigem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idFornecedor {
            get {
                return this.idFornecedorField;
            }
            set {
                if ((this.idFornecedorField.Equals(value) != true)) {
                    this.idFornecedorField = value;
                    this.RaisePropertyChanged("idFornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imagemDocumento {
            get {
                return this.imagemDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.imagemDocumentoField, value) != true)) {
                    this.imagemDocumentoField = value;
                    this.RaisePropertyChanged("imagemDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroDocumentoField, value) != true)) {
                    this.numeroDocumentoField = value;
                    this.RaisePropertyChanged("numeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<char> pagamentoCompartilhado {
            get {
                return this.pagamentoCompartilhadoField;
            }
            set {
                if ((this.pagamentoCompartilhadoField.Equals(value) != true)) {
                    this.pagamentoCompartilhadoField = value;
                    this.RaisePropertyChanged("pagamentoCompartilhado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> primeiroVencimento {
            get {
                return this.primeiroVencimentoField;
            }
            set {
                if ((this.primeiroVencimentoField.Equals(value) != true)) {
                    this.primeiroVencimentoField = value;
                    this.RaisePropertyChanged("primeiroVencimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantidadeParcela {
            get {
                return this.quantidadeParcelaField;
            }
            set {
                if ((this.quantidadeParcelaField.Equals(value) != true)) {
                    this.quantidadeParcelaField = value;
                    this.RaisePropertyChanged("quantidadeParcela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorPagar {
            get {
                return this.valorPagarField;
            }
            set {
                if ((this.valorPagarField.Equals(value) != true)) {
                    this.valorPagarField = value;
                    this.RaisePropertyChanged("valorPagar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                if ((this.valorTotalField.Equals(value) != true)) {
                    this.valorTotalField = value;
                    this.RaisePropertyChanged("valorTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoOrigemDTO", Namespace="http://schemas.datacontract.org/2004/07/OrcamentoService.Model")]
    [System.SerializableAttribute()]
    public partial class DocumentoOrigemDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siglaDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string siglaDocumento {
            get {
                return this.siglaDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.siglaDocumentoField, value) != true)) {
                    this.siglaDocumentoField = value;
                    this.RaisePropertyChanged("siglaDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParcelaReceberDTO", Namespace="http://schemas.datacontract.org/2004/07/OrcamentoService.Model")]
    [System.SerializableAttribute()]
    public partial class ParcelaReceberDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataEmissaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataVencimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> descontoAteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idStatusParcelaReceberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OrcamentoClient.OrcamentoReference.LancamentoReceberDTO lancamentoReceberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numeroParcelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> taxaDescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> taxaJuroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> taxaMultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorDescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorJuroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorMultaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                if ((this.dataEmissaoField.Equals(value) != true)) {
                    this.dataEmissaoField = value;
                    this.RaisePropertyChanged("dataEmissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataVencimento {
            get {
                return this.dataVencimentoField;
            }
            set {
                if ((this.dataVencimentoField.Equals(value) != true)) {
                    this.dataVencimentoField = value;
                    this.RaisePropertyChanged("dataVencimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> descontoAte {
            get {
                return this.descontoAteField;
            }
            set {
                if ((this.descontoAteField.Equals(value) != true)) {
                    this.descontoAteField = value;
                    this.RaisePropertyChanged("descontoAte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idStatusParcelaReceber {
            get {
                return this.idStatusParcelaReceberField;
            }
            set {
                if ((this.idStatusParcelaReceberField.Equals(value) != true)) {
                    this.idStatusParcelaReceberField = value;
                    this.RaisePropertyChanged("idStatusParcelaReceber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrcamentoClient.OrcamentoReference.LancamentoReceberDTO lancamentoReceber {
            get {
                return this.lancamentoReceberField;
            }
            set {
                if ((object.ReferenceEquals(this.lancamentoReceberField, value) != true)) {
                    this.lancamentoReceberField = value;
                    this.RaisePropertyChanged("lancamentoReceber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numeroParcela {
            get {
                return this.numeroParcelaField;
            }
            set {
                if ((this.numeroParcelaField.Equals(value) != true)) {
                    this.numeroParcelaField = value;
                    this.RaisePropertyChanged("numeroParcela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> taxaDesconto {
            get {
                return this.taxaDescontoField;
            }
            set {
                if ((this.taxaDescontoField.Equals(value) != true)) {
                    this.taxaDescontoField = value;
                    this.RaisePropertyChanged("taxaDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> taxaJuro {
            get {
                return this.taxaJuroField;
            }
            set {
                if ((this.taxaJuroField.Equals(value) != true)) {
                    this.taxaJuroField = value;
                    this.RaisePropertyChanged("taxaJuro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> taxaMulta {
            get {
                return this.taxaMultaField;
            }
            set {
                if ((this.taxaMultaField.Equals(value) != true)) {
                    this.taxaMultaField = value;
                    this.RaisePropertyChanged("taxaMulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valor {
            get {
                return this.valorField;
            }
            set {
                if ((this.valorField.Equals(value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorDesconto {
            get {
                return this.valorDescontoField;
            }
            set {
                if ((this.valorDescontoField.Equals(value) != true)) {
                    this.valorDescontoField = value;
                    this.RaisePropertyChanged("valorDesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorJuro {
            get {
                return this.valorJuroField;
            }
            set {
                if ((this.valorJuroField.Equals(value) != true)) {
                    this.valorJuroField = value;
                    this.RaisePropertyChanged("valorJuro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorMulta {
            get {
                return this.valorMultaField;
            }
            set {
                if ((this.valorMultaField.Equals(value) != true)) {
                    this.valorMultaField = value;
                    this.RaisePropertyChanged("valorMulta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LancamentoReceberDTO", Namespace="http://schemas.datacontract.org/2004/07/OrcamentoService.Model")]
    [System.SerializableAttribute()]
    public partial class LancamentoReceberDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataLancamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OrcamentoClient.OrcamentoReference.DocumentoOrigemDTO documentoOrigemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> primeiroVencimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> quantidadeParcelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorReceberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataLancamento {
            get {
                return this.dataLancamentoField;
            }
            set {
                if ((this.dataLancamentoField.Equals(value) != true)) {
                    this.dataLancamentoField = value;
                    this.RaisePropertyChanged("dataLancamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrcamentoClient.OrcamentoReference.DocumentoOrigemDTO documentoOrigem {
            get {
                return this.documentoOrigemField;
            }
            set {
                if ((object.ReferenceEquals(this.documentoOrigemField, value) != true)) {
                    this.documentoOrigemField = value;
                    this.RaisePropertyChanged("documentoOrigem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idCliente {
            get {
                return this.idClienteField;
            }
            set {
                if ((this.idClienteField.Equals(value) != true)) {
                    this.idClienteField = value;
                    this.RaisePropertyChanged("idCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroDocumentoField, value) != true)) {
                    this.numeroDocumentoField = value;
                    this.RaisePropertyChanged("numeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> primeiroVencimento {
            get {
                return this.primeiroVencimentoField;
            }
            set {
                if ((this.primeiroVencimentoField.Equals(value) != true)) {
                    this.primeiroVencimentoField = value;
                    this.RaisePropertyChanged("primeiroVencimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quantidadeParcela {
            get {
                return this.quantidadeParcelaField;
            }
            set {
                if ((this.quantidadeParcelaField.Equals(value) != true)) {
                    this.quantidadeParcelaField = value;
                    this.RaisePropertyChanged("quantidadeParcela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorReceber {
            get {
                return this.valorReceberField;
            }
            set {
                if ((this.valorReceberField.Equals(value) != true)) {
                    this.valorReceberField = value;
                    this.RaisePropertyChanged("valorReceber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                if ((this.valorTotalField.Equals(value) != true)) {
                    this.valorTotalField = value;
                    this.RaisePropertyChanged("valorTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrcamentoDTO", Namespace="http://schemas.datacontract.org/2004/07/OrcamentoService.Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class OrcamentoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.OrcamentoDetalheDTO> listaOrcamentoDetalheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numeroPeriodosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OrcamentoClient.OrcamentoReference.OrcamentoPeriodoDTO orcamentoPeriodoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataBase {
            get {
                return this.dataBaseField;
            }
            set {
                if ((this.dataBaseField.Equals(value) != true)) {
                    this.dataBaseField = value;
                    this.RaisePropertyChanged("dataBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataInicial {
            get {
                return this.dataInicialField;
            }
            set {
                if ((this.dataInicialField.Equals(value) != true)) {
                    this.dataInicialField = value;
                    this.RaisePropertyChanged("dataInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.OrcamentoDetalheDTO> listaOrcamentoDetalhe {
            get {
                return this.listaOrcamentoDetalheField;
            }
            set {
                if ((object.ReferenceEquals(this.listaOrcamentoDetalheField, value) != true)) {
                    this.listaOrcamentoDetalheField = value;
                    this.RaisePropertyChanged("listaOrcamentoDetalhe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numeroPeriodos {
            get {
                return this.numeroPeriodosField;
            }
            set {
                if ((this.numeroPeriodosField.Equals(value) != true)) {
                    this.numeroPeriodosField = value;
                    this.RaisePropertyChanged("numeroPeriodos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrcamentoClient.OrcamentoReference.OrcamentoPeriodoDTO orcamentoPeriodo {
            get {
                return this.orcamentoPeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.orcamentoPeriodoField, value) != true)) {
                    this.orcamentoPeriodoField = value;
                    this.RaisePropertyChanged("orcamentoPeriodo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrcamentoDetalheDTO", Namespace="http://schemas.datacontract.org/2004/07/OrcamentoService.Model")]
    [System.SerializableAttribute()]
    public partial class OrcamentoDetalheDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OrcamentoClient.OrcamentoReference.NaturezaFinanceiraDTO naturezaFinanceiraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OrcamentoClient.OrcamentoReference.OrcamentoDTO orcamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string periodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> taxaVariacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorOrcadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorRealizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorVariacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrcamentoClient.OrcamentoReference.NaturezaFinanceiraDTO naturezaFinanceira {
            get {
                return this.naturezaFinanceiraField;
            }
            set {
                if ((object.ReferenceEquals(this.naturezaFinanceiraField, value) != true)) {
                    this.naturezaFinanceiraField = value;
                    this.RaisePropertyChanged("naturezaFinanceira");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrcamentoClient.OrcamentoReference.OrcamentoDTO orcamento {
            get {
                return this.orcamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.orcamentoField, value) != true)) {
                    this.orcamentoField = value;
                    this.RaisePropertyChanged("orcamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string periodo {
            get {
                return this.periodoField;
            }
            set {
                if ((object.ReferenceEquals(this.periodoField, value) != true)) {
                    this.periodoField = value;
                    this.RaisePropertyChanged("periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> taxaVariacao {
            get {
                return this.taxaVariacaoField;
            }
            set {
                if ((this.taxaVariacaoField.Equals(value) != true)) {
                    this.taxaVariacaoField = value;
                    this.RaisePropertyChanged("taxaVariacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorOrcado {
            get {
                return this.valorOrcadoField;
            }
            set {
                if ((this.valorOrcadoField.Equals(value) != true)) {
                    this.valorOrcadoField = value;
                    this.RaisePropertyChanged("valorOrcado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorRealizado {
            get {
                return this.valorRealizadoField;
            }
            set {
                if ((this.valorRealizadoField.Equals(value) != true)) {
                    this.valorRealizadoField = value;
                    this.RaisePropertyChanged("valorRealizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valorVariacao {
            get {
                return this.valorVariacaoField;
            }
            set {
                if ((this.valorVariacaoField.Equals(value) != true)) {
                    this.valorVariacaoField = value;
                    this.RaisePropertyChanged("valorVariacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDTO", Namespace="http://schemas.datacontract.org/2004/07/OrcamentoService.Model")]
    [System.SerializableAttribute()]
    public partial class UsuarioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdColaboradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPapelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Administrador {
            get {
                return this.AdministradorField;
            }
            set {
                if ((object.ReferenceEquals(this.AdministradorField, value) != true)) {
                    this.AdministradorField = value;
                    this.RaisePropertyChanged("Administrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdColaborador {
            get {
                return this.IdColaboradorField;
            }
            set {
                if ((this.IdColaboradorField.Equals(value) != true)) {
                    this.IdColaboradorField = value;
                    this.RaisePropertyChanged("IdColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPapel {
            get {
                return this.IdPapelField;
            }
            set {
                if ((this.IdPapelField.Equals(value) != true)) {
                    this.IdPapelField = value;
                    this.RaisePropertyChanged("IdPapel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewControleAcessoDTO", Namespace="http://schemas.datacontract.org/2004/07/OrcamentoService.Model")]
    [System.SerializableAttribute()]
    public partial class ViewControleAcessoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormularioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPapelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formulario {
            get {
                return this.FormularioField;
            }
            set {
                if ((object.ReferenceEquals(this.FormularioField, value) != true)) {
                    this.FormularioField = value;
                    this.RaisePropertyChanged("Formulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((object.ReferenceEquals(this.HabilitadoField, value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncao {
            get {
                return this.IdFuncaoField;
            }
            set {
                if ((this.IdFuncaoField.Equals(value) != true)) {
                    this.IdFuncaoField = value;
                    this.RaisePropertyChanged("IdFuncao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPapel {
            get {
                return this.IdPapelField;
            }
            set {
                if ((this.IdPapelField.Equals(value) != true)) {
                    this.IdPapelField = value;
                    this.RaisePropertyChanged("IdPapel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaDTO", Namespace="http://schemas.datacontract.org/2004/07/OrcamentoService.Model")]
    [System.SerializableAttribute()]
    public partial class EmpresaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliquotaCofinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliquotaPisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliquotaSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnpjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoGpsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoIbgeCidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoIbgeUfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTerceirosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInicioAtividadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInscJuntaComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagemLogotipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoEstadualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoEstadualStField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoJuntaComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoMunicipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeFantasiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazaoSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuframaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoRegimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliquotaCofins {
            get {
                return this.AliquotaCofinsField;
            }
            set {
                if ((object.ReferenceEquals(this.AliquotaCofinsField, value) != true)) {
                    this.AliquotaCofinsField = value;
                    this.RaisePropertyChanged("AliquotaCofins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliquotaPis {
            get {
                return this.AliquotaPisField;
            }
            set {
                if ((object.ReferenceEquals(this.AliquotaPisField, value) != true)) {
                    this.AliquotaPisField = value;
                    this.RaisePropertyChanged("AliquotaPis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliquotaSat {
            get {
                return this.AliquotaSatField;
            }
            set {
                if ((object.ReferenceEquals(this.AliquotaSatField, value) != true)) {
                    this.AliquotaSatField = value;
                    this.RaisePropertyChanged("AliquotaSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cnpj {
            get {
                return this.CnpjField;
            }
            set {
                if ((object.ReferenceEquals(this.CnpjField, value) != true)) {
                    this.CnpjField = value;
                    this.RaisePropertyChanged("Cnpj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoGps {
            get {
                return this.CodigoGpsField;
            }
            set {
                if ((this.CodigoGpsField.Equals(value) != true)) {
                    this.CodigoGpsField = value;
                    this.RaisePropertyChanged("CodigoGps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoIbgeCidade {
            get {
                return this.CodigoIbgeCidadeField;
            }
            set {
                if ((this.CodigoIbgeCidadeField.Equals(value) != true)) {
                    this.CodigoIbgeCidadeField = value;
                    this.RaisePropertyChanged("CodigoIbgeCidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoIbgeUf {
            get {
                return this.CodigoIbgeUfField;
            }
            set {
                if ((this.CodigoIbgeUfField.Equals(value) != true)) {
                    this.CodigoIbgeUfField = value;
                    this.RaisePropertyChanged("CodigoIbgeUf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTerceiros {
            get {
                return this.CodigoTerceirosField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTerceirosField, value) != true)) {
                    this.CodigoTerceirosField = value;
                    this.RaisePropertyChanged("CodigoTerceiros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contato {
            get {
                return this.ContatoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContatoField, value) != true)) {
                    this.ContatoField = value;
                    this.RaisePropertyChanged("Contato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Crt {
            get {
                return this.CrtField;
            }
            set {
                if ((object.ReferenceEquals(this.CrtField, value) != true)) {
                    this.CrtField = value;
                    this.RaisePropertyChanged("Crt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInicioAtividades {
            get {
                return this.DataInicioAtividadesField;
            }
            set {
                if ((this.DataInicioAtividadesField.Equals(value) != true)) {
                    this.DataInicioAtividadesField = value;
                    this.RaisePropertyChanged("DataInicioAtividades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInscJuntaComercial {
            get {
                return this.DataInscJuntaComercialField;
            }
            set {
                if ((this.DataInscJuntaComercialField.Equals(value) != true)) {
                    this.DataInscJuntaComercialField = value;
                    this.RaisePropertyChanged("DataInscJuntaComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagemLogotipo {
            get {
                return this.ImagemLogotipoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemLogotipoField, value) != true)) {
                    this.ImagemLogotipoField = value;
                    this.RaisePropertyChanged("ImagemLogotipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoEstadual {
            get {
                return this.InscricaoEstadualField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoEstadualField, value) != true)) {
                    this.InscricaoEstadualField = value;
                    this.RaisePropertyChanged("InscricaoEstadual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoEstadualSt {
            get {
                return this.InscricaoEstadualStField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoEstadualStField, value) != true)) {
                    this.InscricaoEstadualStField = value;
                    this.RaisePropertyChanged("InscricaoEstadualSt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoJuntaComercial {
            get {
                return this.InscricaoJuntaComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoJuntaComercialField, value) != true)) {
                    this.InscricaoJuntaComercialField = value;
                    this.RaisePropertyChanged("InscricaoJuntaComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoMunicipal {
            get {
                return this.InscricaoMunicipalField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoMunicipalField, value) != true)) {
                    this.InscricaoMunicipalField = value;
                    this.RaisePropertyChanged("InscricaoMunicipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeFantasia {
            get {
                return this.NomeFantasiaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeFantasiaField, value) != true)) {
                    this.NomeFantasiaField = value;
                    this.RaisePropertyChanged("NomeFantasia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazaoSocial {
            get {
                return this.RazaoSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazaoSocialField, value) != true)) {
                    this.RazaoSocialField = value;
                    this.RaisePropertyChanged("RazaoSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suframa {
            get {
                return this.SuframaField;
            }
            set {
                if ((object.ReferenceEquals(this.SuframaField, value) != true)) {
                    this.SuframaField = value;
                    this.RaisePropertyChanged("Suframa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoRegime {
            get {
                return this.TipoRegimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoRegimeField, value) != true)) {
                    this.TipoRegimeField = value;
                    this.RaisePropertyChanged("TipoRegime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrcamentoReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectPeriodo", ReplyAction="http://tempuri.org/IService/selectPeriodoResponse")]
        System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.OrcamentoPeriodoDTO> selectPeriodo(OrcamentoClient.OrcamentoReference.OrcamentoPeriodoDTO periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectNaturezaFinanceira", ReplyAction="http://tempuri.org/IService/selectNaturezaFinanceiraResponse")]
        System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.NaturezaFinanceiraDTO> selectNaturezaFinanceira(OrcamentoClient.OrcamentoReference.NaturezaFinanceiraDTO naturezaFinanceira);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectLancamentosPagar", ReplyAction="http://tempuri.org/IService/selectLancamentosPagarResponse")]
        System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.ParcelaPagarDTO> selectLancamentosPagar(System.DateTime dataInicio, System.DateTime dataFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectLancamentosReceber", ReplyAction="http://tempuri.org/IService/selectLancamentosReceberResponse")]
        System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.ParcelaReceberDTO> selectLancamentosReceber(System.DateTime dataInicio, System.DateTime dataFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectOrcamento", ReplyAction="http://tempuri.org/IService/selectOrcamentoResponse")]
        System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.OrcamentoDTO> selectOrcamento(OrcamentoClient.OrcamentoReference.OrcamentoDTO orcamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectOrcamentoCompleto", ReplyAction="http://tempuri.org/IService/selectOrcamentoCompletoResponse")]
        OrcamentoClient.OrcamentoReference.OrcamentoDTO selectOrcamentoCompleto(OrcamentoClient.OrcamentoReference.OrcamentoDTO orcamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/saveOrcamento", ReplyAction="http://tempuri.org/IService/saveOrcamentoResponse")]
        OrcamentoClient.OrcamentoReference.OrcamentoDTO saveOrcamento(OrcamentoClient.OrcamentoReference.OrcamentoDTO orcamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectUsuario", ReplyAction="http://tempuri.org/IService/selectUsuarioResponse")]
        OrcamentoClient.OrcamentoReference.UsuarioDTO selectUsuario(string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectControleAcesso", ReplyAction="http://tempuri.org/IService/selectControleAcessoResponse")]
        System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.ViewControleAcessoDTO> selectControleAcesso(OrcamentoClient.OrcamentoReference.ViewControleAcessoDTO viewControleAcesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectEmpresaId", ReplyAction="http://tempuri.org/IService/selectEmpresaIdResponse")]
        OrcamentoClient.OrcamentoReference.EmpresaDTO selectEmpresaId(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : OrcamentoClient.OrcamentoReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<OrcamentoClient.OrcamentoReference.IService>, OrcamentoClient.OrcamentoReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.OrcamentoPeriodoDTO> selectPeriodo(OrcamentoClient.OrcamentoReference.OrcamentoPeriodoDTO periodo) {
            return base.Channel.selectPeriodo(periodo);
        }
        
        public System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.NaturezaFinanceiraDTO> selectNaturezaFinanceira(OrcamentoClient.OrcamentoReference.NaturezaFinanceiraDTO naturezaFinanceira) {
            return base.Channel.selectNaturezaFinanceira(naturezaFinanceira);
        }
        
        public System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.ParcelaPagarDTO> selectLancamentosPagar(System.DateTime dataInicio, System.DateTime dataFim) {
            return base.Channel.selectLancamentosPagar(dataInicio, dataFim);
        }
        
        public System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.ParcelaReceberDTO> selectLancamentosReceber(System.DateTime dataInicio, System.DateTime dataFim) {
            return base.Channel.selectLancamentosReceber(dataInicio, dataFim);
        }
        
        public System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.OrcamentoDTO> selectOrcamento(OrcamentoClient.OrcamentoReference.OrcamentoDTO orcamento) {
            return base.Channel.selectOrcamento(orcamento);
        }
        
        public OrcamentoClient.OrcamentoReference.OrcamentoDTO selectOrcamentoCompleto(OrcamentoClient.OrcamentoReference.OrcamentoDTO orcamento) {
            return base.Channel.selectOrcamentoCompleto(orcamento);
        }
        
        public OrcamentoClient.OrcamentoReference.OrcamentoDTO saveOrcamento(OrcamentoClient.OrcamentoReference.OrcamentoDTO orcamento) {
            return base.Channel.saveOrcamento(orcamento);
        }
        
        public OrcamentoClient.OrcamentoReference.UsuarioDTO selectUsuario(string login, string senha) {
            return base.Channel.selectUsuario(login, senha);
        }
        
        public System.Collections.Generic.List<OrcamentoClient.OrcamentoReference.ViewControleAcessoDTO> selectControleAcesso(OrcamentoClient.OrcamentoReference.ViewControleAcessoDTO viewControleAcesso) {
            return base.Channel.selectControleAcesso(viewControleAcesso);
        }
        
        public OrcamentoClient.OrcamentoReference.EmpresaDTO selectEmpresaId(int id) {
            return base.Channel.selectEmpresaId(id);
        }
    }
}
