//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContratosClient.GEDServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GEDServiceReference.IGEDService")]
    public interface IGEDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/deleteGedTipoDocumento", ReplyAction="http://tempuri.org/IGEDService/deleteGedTipoDocumentoResponse")]
        int deleteGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/salvarAtualizarGedTipoDocumento", ReplyAction="http://tempuri.org/IGEDService/salvarAtualizarGedTipoDocumentoResponse")]
        GEDClient.GEDServiceReference.GedTipoDocumentoDTO salvarAtualizarGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectGedTipoDocumento", ReplyAction="http://tempuri.org/IGEDService/selectGedTipoDocumentoResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedTipoDocumentoDTO> selectGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectGedTipoDocumentoPagina", ReplyAction="http://tempuri.org/IGEDService/selectGedTipoDocumentoPaginaResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedTipoDocumentoDTO> selectGedTipoDocumentoPagina(int primeiroResultado, int quantidadeResultados, GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/saveDocumento", ReplyAction="http://tempuri.org/IGEDService/saveDocumentoResponse")]
        GEDClient.GEDServiceReference.GedDocumentoDTO saveDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/updateDocumento", ReplyAction="http://tempuri.org/IGEDService/updateDocumentoResponse")]
        GEDClient.GEDServiceReference.GedDocumentoDTO updateDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/deleteDocumento", ReplyAction="http://tempuri.org/IGEDService/deleteDocumentoResponse")]
        int deleteDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectDocumento", ReplyAction="http://tempuri.org/IGEDService/selectDocumentoResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedDocumentoDTO> selectDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectDocumentoId", ReplyAction="http://tempuri.org/IGEDService/selectDocumentoIdResponse")]
        GEDClient.GEDServiceReference.GedDocumentoDTO selectDocumentoId(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/deleteGedVersaoDocumento", ReplyAction="http://tempuri.org/IGEDService/deleteGedVersaoDocumentoResponse")]
        int deleteGedVersaoDocumento(GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/salvarAtualizarGedVersaoDocumento", ReplyAction="http://tempuri.org/IGEDService/salvarAtualizarGedVersaoDocumentoResponse")]
        GEDClient.GEDServiceReference.GedVersaoDocumentoDTO salvarAtualizarGedVersaoDocumento(GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectGedVersaoDocumento", ReplyAction="http://tempuri.org/IGEDService/selectGedVersaoDocumentoResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedVersaoDocumentoDTO> selectGedVersaoDocumento(GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectGedVersaoDocumentoPagina", ReplyAction="http://tempuri.org/IGEDService/selectGedVersaoDocumentoPaginaResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedVersaoDocumentoDTO> selectGedVersaoDocumentoPagina(int primeiroResultado, int quantidadeResultados, GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectUsuario", ReplyAction="http://tempuri.org/IGEDService/selectUsuarioResponse")]
        GEDClient.GEDServiceReference.UsuarioDTO selectUsuario(string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectControleAcesso", ReplyAction="http://tempuri.org/IGEDService/selectControleAcessoResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.ViewControleAcessoDTO> selectControleAcesso(GEDClient.GEDServiceReference.ViewControleAcessoDTO viewControleAcesso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGEDServiceChannel : ContratosClient.GEDServiceReference.IGEDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GEDServiceClient : System.ServiceModel.ClientBase<ContratosClient.GEDServiceReference.IGEDService>, ContratosClient.GEDServiceReference.IGEDService {
        
        public GEDServiceClient() {
        }
        
        public GEDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GEDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GEDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GEDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int deleteGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento) {
            return base.Channel.deleteGedTipoDocumento(gedTipoDocumento);
        }
        
        public GEDClient.GEDServiceReference.GedTipoDocumentoDTO salvarAtualizarGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento) {
            return base.Channel.salvarAtualizarGedTipoDocumento(gedTipoDocumento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedTipoDocumentoDTO> selectGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento) {
            return base.Channel.selectGedTipoDocumento(gedTipoDocumento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedTipoDocumentoDTO> selectGedTipoDocumentoPagina(int primeiroResultado, int quantidadeResultados, GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento) {
            return base.Channel.selectGedTipoDocumentoPagina(primeiroResultado, quantidadeResultados, gedTipoDocumento);
        }
        
        public GEDClient.GEDServiceReference.GedDocumentoDTO saveDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.saveDocumento(documento);
        }
        
        public GEDClient.GEDServiceReference.GedDocumentoDTO updateDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.updateDocumento(documento);
        }
        
        public int deleteDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.deleteDocumento(documento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedDocumentoDTO> selectDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.selectDocumento(documento);
        }
        
        public GEDClient.GEDServiceReference.GedDocumentoDTO selectDocumentoId(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.selectDocumentoId(documento);
        }
        
        public int deleteGedVersaoDocumento(GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento) {
            return base.Channel.deleteGedVersaoDocumento(gedVersaoDocumento);
        }
        
        public GEDClient.GEDServiceReference.GedVersaoDocumentoDTO salvarAtualizarGedVersaoDocumento(GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento) {
            return base.Channel.salvarAtualizarGedVersaoDocumento(gedVersaoDocumento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedVersaoDocumentoDTO> selectGedVersaoDocumento(GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento) {
            return base.Channel.selectGedVersaoDocumento(gedVersaoDocumento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedVersaoDocumentoDTO> selectGedVersaoDocumentoPagina(int primeiroResultado, int quantidadeResultados, GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento) {
            return base.Channel.selectGedVersaoDocumentoPagina(primeiroResultado, quantidadeResultados, gedVersaoDocumento);
        }
        
        public GEDClient.GEDServiceReference.UsuarioDTO selectUsuario(string login, string senha) {
            return base.Channel.selectUsuario(login, senha);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.ViewControleAcessoDTO> selectControleAcesso(GEDClient.GEDServiceReference.ViewControleAcessoDTO viewControleAcesso) {
            return base.Channel.selectControleAcesso(viewControleAcesso);
        }
    }
}
