//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEDClient.GEDServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GedTipoDocumentoDTO", Namespace="http://schemas.datacontract.org/2004/07/GEDService.Model")]
    [System.SerializableAttribute()]
    public partial class GedTipoDocumentoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GEDClient.GEDServiceReference.EmpresaDTO EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TamanhoMaximoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GEDClient.GEDServiceReference.EmpresaDTO Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TamanhoMaximo {
            get {
                return this.TamanhoMaximoField;
            }
            set {
                if ((this.TamanhoMaximoField.Equals(value) != true)) {
                    this.TamanhoMaximoField = value;
                    this.RaisePropertyChanged("TamanhoMaximo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaDTO", Namespace="http://schemas.datacontract.org/2004/07/GEDService.Model")]
    [System.SerializableAttribute()]
    public partial class EmpresaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliquotaCofinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliquotaPisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliquotaSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnpjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoGpsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoIbgeCidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoIbgeUfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTerceirosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInicioAtividadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInscJuntaComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagemLogotipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoEstadualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoEstadualStField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoJuntaComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoMunicipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeFantasiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazaoSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuframaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoRegimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliquotaCofins {
            get {
                return this.AliquotaCofinsField;
            }
            set {
                if ((object.ReferenceEquals(this.AliquotaCofinsField, value) != true)) {
                    this.AliquotaCofinsField = value;
                    this.RaisePropertyChanged("AliquotaCofins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliquotaPis {
            get {
                return this.AliquotaPisField;
            }
            set {
                if ((object.ReferenceEquals(this.AliquotaPisField, value) != true)) {
                    this.AliquotaPisField = value;
                    this.RaisePropertyChanged("AliquotaPis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliquotaSat {
            get {
                return this.AliquotaSatField;
            }
            set {
                if ((object.ReferenceEquals(this.AliquotaSatField, value) != true)) {
                    this.AliquotaSatField = value;
                    this.RaisePropertyChanged("AliquotaSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cnpj {
            get {
                return this.CnpjField;
            }
            set {
                if ((object.ReferenceEquals(this.CnpjField, value) != true)) {
                    this.CnpjField = value;
                    this.RaisePropertyChanged("Cnpj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoGps {
            get {
                return this.CodigoGpsField;
            }
            set {
                if ((this.CodigoGpsField.Equals(value) != true)) {
                    this.CodigoGpsField = value;
                    this.RaisePropertyChanged("CodigoGps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoIbgeCidade {
            get {
                return this.CodigoIbgeCidadeField;
            }
            set {
                if ((this.CodigoIbgeCidadeField.Equals(value) != true)) {
                    this.CodigoIbgeCidadeField = value;
                    this.RaisePropertyChanged("CodigoIbgeCidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoIbgeUf {
            get {
                return this.CodigoIbgeUfField;
            }
            set {
                if ((this.CodigoIbgeUfField.Equals(value) != true)) {
                    this.CodigoIbgeUfField = value;
                    this.RaisePropertyChanged("CodigoIbgeUf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTerceiros {
            get {
                return this.CodigoTerceirosField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTerceirosField, value) != true)) {
                    this.CodigoTerceirosField = value;
                    this.RaisePropertyChanged("CodigoTerceiros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contato {
            get {
                return this.ContatoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContatoField, value) != true)) {
                    this.ContatoField = value;
                    this.RaisePropertyChanged("Contato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Crt {
            get {
                return this.CrtField;
            }
            set {
                if ((object.ReferenceEquals(this.CrtField, value) != true)) {
                    this.CrtField = value;
                    this.RaisePropertyChanged("Crt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInicioAtividades {
            get {
                return this.DataInicioAtividadesField;
            }
            set {
                if ((this.DataInicioAtividadesField.Equals(value) != true)) {
                    this.DataInicioAtividadesField = value;
                    this.RaisePropertyChanged("DataInicioAtividades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInscJuntaComercial {
            get {
                return this.DataInscJuntaComercialField;
            }
            set {
                if ((this.DataInscJuntaComercialField.Equals(value) != true)) {
                    this.DataInscJuntaComercialField = value;
                    this.RaisePropertyChanged("DataInscJuntaComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagemLogotipo {
            get {
                return this.ImagemLogotipoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemLogotipoField, value) != true)) {
                    this.ImagemLogotipoField = value;
                    this.RaisePropertyChanged("ImagemLogotipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoEstadual {
            get {
                return this.InscricaoEstadualField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoEstadualField, value) != true)) {
                    this.InscricaoEstadualField = value;
                    this.RaisePropertyChanged("InscricaoEstadual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoEstadualSt {
            get {
                return this.InscricaoEstadualStField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoEstadualStField, value) != true)) {
                    this.InscricaoEstadualStField = value;
                    this.RaisePropertyChanged("InscricaoEstadualSt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoJuntaComercial {
            get {
                return this.InscricaoJuntaComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoJuntaComercialField, value) != true)) {
                    this.InscricaoJuntaComercialField = value;
                    this.RaisePropertyChanged("InscricaoJuntaComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoMunicipal {
            get {
                return this.InscricaoMunicipalField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoMunicipalField, value) != true)) {
                    this.InscricaoMunicipalField = value;
                    this.RaisePropertyChanged("InscricaoMunicipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeFantasia {
            get {
                return this.NomeFantasiaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeFantasiaField, value) != true)) {
                    this.NomeFantasiaField = value;
                    this.RaisePropertyChanged("NomeFantasia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazaoSocial {
            get {
                return this.RazaoSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazaoSocialField, value) != true)) {
                    this.RazaoSocialField = value;
                    this.RaisePropertyChanged("RazaoSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suframa {
            get {
                return this.SuframaField;
            }
            set {
                if ((object.ReferenceEquals(this.SuframaField, value) != true)) {
                    this.SuframaField = value;
                    this.RaisePropertyChanged("Suframa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoRegime {
            get {
                return this.TipoRegimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoRegimeField, value) != true)) {
                    this.TipoRegimeField = value;
                    this.RaisePropertyChanged("TipoRegime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GedDocumentoDTO", Namespace="http://schemas.datacontract.org/2004/07/GEDService.Model")]
    [System.SerializableAttribute()]
    public partial class GedDocumentoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssinadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataExclusaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataFimVigenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GEDClient.GEDServiceReference.EmpresaDTO EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GEDClient.GEDServiceReference.GedTipoDocumentoDTO GedTipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PalavraChaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PodeAlterarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PodeExcluirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GEDClient.GEDServiceReference.ArquivoDTO arquivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Assinado {
            get {
                return this.AssinadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AssinadoField, value) != true)) {
                    this.AssinadoField = value;
                    this.RaisePropertyChanged("Assinado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataExclusao {
            get {
                return this.DataExclusaoField;
            }
            set {
                if ((this.DataExclusaoField.Equals(value) != true)) {
                    this.DataExclusaoField = value;
                    this.RaisePropertyChanged("DataExclusao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataFimVigencia {
            get {
                return this.DataFimVigenciaField;
            }
            set {
                if ((this.DataFimVigenciaField.Equals(value) != true)) {
                    this.DataFimVigenciaField = value;
                    this.RaisePropertyChanged("DataFimVigencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GEDClient.GEDServiceReference.EmpresaDTO Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GEDClient.GEDServiceReference.GedTipoDocumentoDTO GedTipoDocumento {
            get {
                return this.GedTipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.GedTipoDocumentoField, value) != true)) {
                    this.GedTipoDocumentoField = value;
                    this.RaisePropertyChanged("GedTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PalavraChave {
            get {
                return this.PalavraChaveField;
            }
            set {
                if ((object.ReferenceEquals(this.PalavraChaveField, value) != true)) {
                    this.PalavraChaveField = value;
                    this.RaisePropertyChanged("PalavraChave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PodeAlterar {
            get {
                return this.PodeAlterarField;
            }
            set {
                if ((object.ReferenceEquals(this.PodeAlterarField, value) != true)) {
                    this.PodeAlterarField = value;
                    this.RaisePropertyChanged("PodeAlterar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PodeExcluir {
            get {
                return this.PodeExcluirField;
            }
            set {
                if ((object.ReferenceEquals(this.PodeExcluirField, value) != true)) {
                    this.PodeExcluirField = value;
                    this.RaisePropertyChanged("PodeExcluir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GEDClient.GEDServiceReference.ArquivoDTO arquivo {
            get {
                return this.arquivoField;
            }
            set {
                if ((object.ReferenceEquals(this.arquivoField, value) != true)) {
                    this.arquivoField = value;
                    this.RaisePropertyChanged("arquivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArquivoDTO", Namespace="http://schemas.datacontract.org/2004/07/GEDService.Model")]
    [System.SerializableAttribute()]
    public partial class ArquivoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.FileInfo fileInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.MemoryStream memoryStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.MemoryStream streamAssinaturaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.FileInfo fileInfo {
            get {
                return this.fileInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.fileInfoField, value) != true)) {
                    this.fileInfoField = value;
                    this.RaisePropertyChanged("fileInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.MemoryStream memoryStream {
            get {
                return this.memoryStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.memoryStreamField, value) != true)) {
                    this.memoryStreamField = value;
                    this.RaisePropertyChanged("memoryStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.MemoryStream streamAssinatura {
            get {
                return this.streamAssinaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.streamAssinaturaField, value) != true)) {
                    this.streamAssinaturaField = value;
                    this.RaisePropertyChanged("streamAssinatura");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GedVersaoDocumentoDTO", Namespace="http://schemas.datacontract.org/2004/07/GEDService.Model")]
    [System.SerializableAttribute()]
    public partial class GedVersaoDocumentoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaminhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashArquivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdColaboradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Acao {
            get {
                return this.AcaoField;
            }
            set {
                if ((object.ReferenceEquals(this.AcaoField, value) != true)) {
                    this.AcaoField = value;
                    this.RaisePropertyChanged("Acao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caminho {
            get {
                return this.CaminhoField;
            }
            set {
                if ((object.ReferenceEquals(this.CaminhoField, value) != true)) {
                    this.CaminhoField = value;
                    this.RaisePropertyChanged("Caminho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataHora {
            get {
                return this.DataHoraField;
            }
            set {
                if ((this.DataHoraField.Equals(value) != true)) {
                    this.DataHoraField = value;
                    this.RaisePropertyChanged("DataHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashArquivo {
            get {
                return this.HashArquivoField;
            }
            set {
                if ((object.ReferenceEquals(this.HashArquivoField, value) != true)) {
                    this.HashArquivoField = value;
                    this.RaisePropertyChanged("HashArquivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdColaborador {
            get {
                return this.IdColaboradorField;
            }
            set {
                if ((this.IdColaboradorField.Equals(value) != true)) {
                    this.IdColaboradorField = value;
                    this.RaisePropertyChanged("IdColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDocumento {
            get {
                return this.IdDocumentoField;
            }
            set {
                if ((this.IdDocumentoField.Equals(value) != true)) {
                    this.IdDocumentoField = value;
                    this.RaisePropertyChanged("IdDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Versao {
            get {
                return this.VersaoField;
            }
            set {
                if ((this.VersaoField.Equals(value) != true)) {
                    this.VersaoField = value;
                    this.RaisePropertyChanged("Versao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDTO", Namespace="http://schemas.datacontract.org/2004/07/GEDService.Model")]
    [System.SerializableAttribute()]
    public partial class UsuarioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdColaboradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPapelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Administrador {
            get {
                return this.AdministradorField;
            }
            set {
                if ((object.ReferenceEquals(this.AdministradorField, value) != true)) {
                    this.AdministradorField = value;
                    this.RaisePropertyChanged("Administrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdColaborador {
            get {
                return this.IdColaboradorField;
            }
            set {
                if ((this.IdColaboradorField.Equals(value) != true)) {
                    this.IdColaboradorField = value;
                    this.RaisePropertyChanged("IdColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPapel {
            get {
                return this.IdPapelField;
            }
            set {
                if ((this.IdPapelField.Equals(value) != true)) {
                    this.IdPapelField = value;
                    this.RaisePropertyChanged("IdPapel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewControleAcessoDTO", Namespace="http://schemas.datacontract.org/2004/07/GEDService.Model")]
    [System.SerializableAttribute()]
    public partial class ViewControleAcessoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormularioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPapelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formulario {
            get {
                return this.FormularioField;
            }
            set {
                if ((object.ReferenceEquals(this.FormularioField, value) != true)) {
                    this.FormularioField = value;
                    this.RaisePropertyChanged("Formulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((object.ReferenceEquals(this.HabilitadoField, value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncao {
            get {
                return this.IdFuncaoField;
            }
            set {
                if ((this.IdFuncaoField.Equals(value) != true)) {
                    this.IdFuncaoField = value;
                    this.RaisePropertyChanged("IdFuncao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPapel {
            get {
                return this.IdPapelField;
            }
            set {
                if ((this.IdPapelField.Equals(value) != true)) {
                    this.IdPapelField = value;
                    this.RaisePropertyChanged("IdPapel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GEDServiceReference.IGEDService")]
    public interface IGEDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/deleteGedTipoDocumento", ReplyAction="http://tempuri.org/IGEDService/deleteGedTipoDocumentoResponse")]
        int deleteGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/salvarAtualizarGedTipoDocumento", ReplyAction="http://tempuri.org/IGEDService/salvarAtualizarGedTipoDocumentoResponse")]
        GEDClient.GEDServiceReference.GedTipoDocumentoDTO salvarAtualizarGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectGedTipoDocumento", ReplyAction="http://tempuri.org/IGEDService/selectGedTipoDocumentoResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedTipoDocumentoDTO> selectGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectGedTipoDocumentoPagina", ReplyAction="http://tempuri.org/IGEDService/selectGedTipoDocumentoPaginaResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedTipoDocumentoDTO> selectGedTipoDocumentoPagina(int primeiroResultado, int quantidadeResultados, GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/saveDocumento", ReplyAction="http://tempuri.org/IGEDService/saveDocumentoResponse")]
        GEDClient.GEDServiceReference.GedDocumentoDTO saveDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/updateDocumento", ReplyAction="http://tempuri.org/IGEDService/updateDocumentoResponse")]
        GEDClient.GEDServiceReference.GedDocumentoDTO updateDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/deleteDocumento", ReplyAction="http://tempuri.org/IGEDService/deleteDocumentoResponse")]
        int deleteDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectDocumento", ReplyAction="http://tempuri.org/IGEDService/selectDocumentoResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedDocumentoDTO> selectDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectDocumentoId", ReplyAction="http://tempuri.org/IGEDService/selectDocumentoIdResponse")]
        GEDClient.GEDServiceReference.GedDocumentoDTO selectDocumentoId(GEDClient.GEDServiceReference.GedDocumentoDTO documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/deleteGedVersaoDocumento", ReplyAction="http://tempuri.org/IGEDService/deleteGedVersaoDocumentoResponse")]
        int deleteGedVersaoDocumento(GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/salvarAtualizarGedVersaoDocumento", ReplyAction="http://tempuri.org/IGEDService/salvarAtualizarGedVersaoDocumentoResponse")]
        GEDClient.GEDServiceReference.GedVersaoDocumentoDTO salvarAtualizarGedVersaoDocumento(GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectGedVersaoDocumento", ReplyAction="http://tempuri.org/IGEDService/selectGedVersaoDocumentoResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedVersaoDocumentoDTO> selectGedVersaoDocumento(GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectGedVersaoDocumentoPagina", ReplyAction="http://tempuri.org/IGEDService/selectGedVersaoDocumentoPaginaResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.GedVersaoDocumentoDTO> selectGedVersaoDocumentoPagina(int primeiroResultado, int quantidadeResultados, GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectUsuario", ReplyAction="http://tempuri.org/IGEDService/selectUsuarioResponse")]
        GEDClient.GEDServiceReference.UsuarioDTO selectUsuario(string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGEDService/selectControleAcesso", ReplyAction="http://tempuri.org/IGEDService/selectControleAcessoResponse")]
        System.Collections.Generic.List<GEDClient.GEDServiceReference.ViewControleAcessoDTO> selectControleAcesso(GEDClient.GEDServiceReference.ViewControleAcessoDTO viewControleAcesso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGEDServiceChannel : GEDClient.GEDServiceReference.IGEDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GEDServiceClient : System.ServiceModel.ClientBase<GEDClient.GEDServiceReference.IGEDService>, GEDClient.GEDServiceReference.IGEDService {
        
        public GEDServiceClient() {
        }
        
        public GEDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GEDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GEDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GEDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int deleteGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento) {
            return base.Channel.deleteGedTipoDocumento(gedTipoDocumento);
        }
        
        public GEDClient.GEDServiceReference.GedTipoDocumentoDTO salvarAtualizarGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento) {
            return base.Channel.salvarAtualizarGedTipoDocumento(gedTipoDocumento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedTipoDocumentoDTO> selectGedTipoDocumento(GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento) {
            return base.Channel.selectGedTipoDocumento(gedTipoDocumento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedTipoDocumentoDTO> selectGedTipoDocumentoPagina(int primeiroResultado, int quantidadeResultados, GEDClient.GEDServiceReference.GedTipoDocumentoDTO gedTipoDocumento) {
            return base.Channel.selectGedTipoDocumentoPagina(primeiroResultado, quantidadeResultados, gedTipoDocumento);
        }
        
        public GEDClient.GEDServiceReference.GedDocumentoDTO saveDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.saveDocumento(documento);
        }
        
        public GEDClient.GEDServiceReference.GedDocumentoDTO updateDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.updateDocumento(documento);
        }
        
        public int deleteDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.deleteDocumento(documento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedDocumentoDTO> selectDocumento(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.selectDocumento(documento);
        }
        
        public GEDClient.GEDServiceReference.GedDocumentoDTO selectDocumentoId(GEDClient.GEDServiceReference.GedDocumentoDTO documento) {
            return base.Channel.selectDocumentoId(documento);
        }
        
        public int deleteGedVersaoDocumento(GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento) {
            return base.Channel.deleteGedVersaoDocumento(gedVersaoDocumento);
        }
        
        public GEDClient.GEDServiceReference.GedVersaoDocumentoDTO salvarAtualizarGedVersaoDocumento(GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento) {
            return base.Channel.salvarAtualizarGedVersaoDocumento(gedVersaoDocumento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedVersaoDocumentoDTO> selectGedVersaoDocumento(GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento) {
            return base.Channel.selectGedVersaoDocumento(gedVersaoDocumento);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.GedVersaoDocumentoDTO> selectGedVersaoDocumentoPagina(int primeiroResultado, int quantidadeResultados, GEDClient.GEDServiceReference.GedVersaoDocumentoDTO gedVersaoDocumento) {
            return base.Channel.selectGedVersaoDocumentoPagina(primeiroResultado, quantidadeResultados, gedVersaoDocumento);
        }
        
        public GEDClient.GEDServiceReference.UsuarioDTO selectUsuario(string login, string senha) {
            return base.Channel.selectUsuario(login, senha);
        }
        
        public System.Collections.Generic.List<GEDClient.GEDServiceReference.ViewControleAcessoDTO> selectControleAcesso(GEDClient.GEDServiceReference.ViewControleAcessoDTO viewControleAcesso) {
            return base.Channel.selectControleAcesso(viewControleAcesso);
        }
    }
}
