//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISClient.ServicoSISReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VendedorDTO", Namespace="http://schemas.datacontract.org/2004/07/SISService.Model")]
    [System.SerializableAttribute()]
    public partial class VendedorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SISClient.ServicoSISReference.LocalVendaDTO LocalVendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SISClient.ServicoSISReference.SituacaoVendedorDTO SituacaoVendedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SISClient.ServicoSISReference.TipoPagamentoDTO TipoPagamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SISClient.ServicoSISReference.LocalVendaDTO LocalVenda {
            get {
                return this.LocalVendaField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalVendaField, value) != true)) {
                    this.LocalVendaField = value;
                    this.RaisePropertyChanged("LocalVenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SISClient.ServicoSISReference.SituacaoVendedorDTO SituacaoVendedor {
            get {
                return this.SituacaoVendedorField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacaoVendedorField, value) != true)) {
                    this.SituacaoVendedorField = value;
                    this.RaisePropertyChanged("SituacaoVendedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SISClient.ServicoSISReference.TipoPagamentoDTO TipoPagamento {
            get {
                return this.TipoPagamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPagamentoField, value) != true)) {
                    this.TipoPagamentoField = value;
                    this.RaisePropertyChanged("TipoPagamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalVendaDTO", Namespace="http://schemas.datacontract.org/2004/07/SISService.Model")]
    [System.SerializableAttribute()]
    public partial class LocalVendaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SituacaoVendedorDTO", Namespace="http://schemas.datacontract.org/2004/07/SISService.Model")]
    [System.SerializableAttribute()]
    public partial class SituacaoVendedorDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPagamentoDTO", Namespace="http://schemas.datacontract.org/2004/07/SISService.Model")]
    [System.SerializableAttribute()]
    public partial class TipoPagamentoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDTO", Namespace="http://schemas.datacontract.org/2004/07/SISService.Model")]
    [System.SerializableAttribute()]
    public partial class UsuarioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPapelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionario {
            get {
                return this.IdFuncionarioField;
            }
            set {
                if ((this.IdFuncionarioField.Equals(value) != true)) {
                    this.IdFuncionarioField = value;
                    this.RaisePropertyChanged("IdFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPapel {
            get {
                return this.IdPapelField;
            }
            set {
                if ((this.IdPapelField.Equals(value) != true)) {
                    this.IdPapelField = value;
                    this.RaisePropertyChanged("IdPapel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewControleAcessoDTO", Namespace="http://schemas.datacontract.org/2004/07/SISService.Model")]
    [System.SerializableAttribute()]
    public partial class ViewControleAcessoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormularioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPapelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formulario {
            get {
                return this.FormularioField;
            }
            set {
                if ((object.ReferenceEquals(this.FormularioField, value) != true)) {
                    this.FormularioField = value;
                    this.RaisePropertyChanged("Formulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((object.ReferenceEquals(this.HabilitadoField, value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncao {
            get {
                return this.IdFuncaoField;
            }
            set {
                if ((this.IdFuncaoField.Equals(value) != true)) {
                    this.IdFuncaoField = value;
                    this.RaisePropertyChanged("IdFuncao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPapel {
            get {
                return this.IdPapelField;
            }
            set {
                if ((this.IdPapelField.Equals(value) != true)) {
                    this.IdPapelField = value;
                    this.RaisePropertyChanged("IdPapel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CargoDTO", Namespace="http://schemas.datacontract.org/2004/07/SISService.Model")]
    [System.SerializableAttribute()]
    public partial class CargoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaProdutoDTO", Namespace="http://schemas.datacontract.org/2004/07/SISService.Model")]
    [System.SerializableAttribute()]
    public partial class CategoriaProdutoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuncionarioDTO", Namespace="http://schemas.datacontract.org/2004/07/SISService.Model")]
    [System.SerializableAttribute()]
    public partial class FuncionarioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SISClient.ServicoSISReference.CargoDTO CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Celular1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Celular2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SISClient.ServicoSISReference.CargoDTO Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular1 {
            get {
                return this.Celular1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Celular1Field, value) != true)) {
                    this.Celular1Field = value;
                    this.RaisePropertyChanged("Celular1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular2 {
            get {
                return this.Celular2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Celular2Field, value) != true)) {
                    this.Celular2Field = value;
                    this.RaisePropertyChanged("Celular2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoDTO", Namespace="http://schemas.datacontract.org/2004/07/SISService.Model")]
    [System.SerializableAttribute()]
    public partial class ProdutoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SISClient.ServicoSISReference.CategoriaProdutoDTO CategoriaProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SISClient.ServicoSISReference.CategoriaProdutoDTO CategoriaProduto {
            get {
                return this.CategoriaProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaProdutoField, value) != true)) {
                    this.CategoriaProdutoField = value;
                    this.RaisePropertyChanged("CategoriaProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoSISReference.IServicoSIS")]
    public interface IServicoSIS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/DeleteVendedor", ReplyAction="http://tempuri.org/IServicoSIS/DeleteVendedorResponse")]
        int DeleteVendedor(SISClient.ServicoSISReference.VendedorDTO vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SalvarAtualizarVendedor", ReplyAction="http://tempuri.org/IServicoSIS/SalvarAtualizarVendedorResponse")]
        SISClient.ServicoSISReference.VendedorDTO SalvarAtualizarVendedor(SISClient.ServicoSISReference.VendedorDTO vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectVendedor", ReplyAction="http://tempuri.org/IServicoSIS/SelectVendedorResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.VendedorDTO> SelectVendedor(SISClient.ServicoSISReference.VendedorDTO vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectVendedorPagina", ReplyAction="http://tempuri.org/IServicoSIS/SelectVendedorPaginaResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.VendedorDTO> SelectVendedorPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.VendedorDTO vendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectUsuario", ReplyAction="http://tempuri.org/IServicoSIS/SelectUsuarioResponse")]
        SISClient.ServicoSISReference.UsuarioDTO SelectUsuario(string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectControleAcesso", ReplyAction="http://tempuri.org/IServicoSIS/SelectControleAcessoResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.ViewControleAcessoDTO> SelectControleAcesso(SISClient.ServicoSISReference.ViewControleAcessoDTO viewControleAcesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/DeleteCargo", ReplyAction="http://tempuri.org/IServicoSIS/DeleteCargoResponse")]
        int DeleteCargo(SISClient.ServicoSISReference.CargoDTO cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SalvarAtualizarCargo", ReplyAction="http://tempuri.org/IServicoSIS/SalvarAtualizarCargoResponse")]
        SISClient.ServicoSISReference.CargoDTO SalvarAtualizarCargo(SISClient.ServicoSISReference.CargoDTO cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectCargo", ReplyAction="http://tempuri.org/IServicoSIS/SelectCargoResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.CargoDTO> SelectCargo(SISClient.ServicoSISReference.CargoDTO cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectCargoPagina", ReplyAction="http://tempuri.org/IServicoSIS/SelectCargoPaginaResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.CargoDTO> SelectCargoPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.CargoDTO cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/DeleteSituacaoVendedor", ReplyAction="http://tempuri.org/IServicoSIS/DeleteSituacaoVendedorResponse")]
        int DeleteSituacaoVendedor(SISClient.ServicoSISReference.SituacaoVendedorDTO situacaoVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SalvarAtualizarSituacaoVendedor", ReplyAction="http://tempuri.org/IServicoSIS/SalvarAtualizarSituacaoVendedorResponse")]
        SISClient.ServicoSISReference.SituacaoVendedorDTO SalvarAtualizarSituacaoVendedor(SISClient.ServicoSISReference.SituacaoVendedorDTO situacaoVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectSituacaoVendedor", ReplyAction="http://tempuri.org/IServicoSIS/SelectSituacaoVendedorResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.SituacaoVendedorDTO> SelectSituacaoVendedor(SISClient.ServicoSISReference.SituacaoVendedorDTO situacaoVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectSituacaoVendedorPagina", ReplyAction="http://tempuri.org/IServicoSIS/SelectSituacaoVendedorPaginaResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.SituacaoVendedorDTO> SelectSituacaoVendedorPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.SituacaoVendedorDTO situacaoVendedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/DeleteCategoriaProduto", ReplyAction="http://tempuri.org/IServicoSIS/DeleteCategoriaProdutoResponse")]
        int DeleteCategoriaProduto(SISClient.ServicoSISReference.CategoriaProdutoDTO categoriaProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SalvarAtualizarCategoriaProduto", ReplyAction="http://tempuri.org/IServicoSIS/SalvarAtualizarCategoriaProdutoResponse")]
        SISClient.ServicoSISReference.CategoriaProdutoDTO SalvarAtualizarCategoriaProduto(SISClient.ServicoSISReference.CategoriaProdutoDTO categoriaProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectCategoriaProduto", ReplyAction="http://tempuri.org/IServicoSIS/SelectCategoriaProdutoResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.CategoriaProdutoDTO> SelectCategoriaProduto(SISClient.ServicoSISReference.CategoriaProdutoDTO categoriaProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectCategoriaProdutoPagina", ReplyAction="http://tempuri.org/IServicoSIS/SelectCategoriaProdutoPaginaResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.CategoriaProdutoDTO> SelectCategoriaProdutoPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.CategoriaProdutoDTO categoriaProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/DeleteTipoPagamento", ReplyAction="http://tempuri.org/IServicoSIS/DeleteTipoPagamentoResponse")]
        int DeleteTipoPagamento(SISClient.ServicoSISReference.TipoPagamentoDTO tipoPagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SalvarAtualizarTipoPagamento", ReplyAction="http://tempuri.org/IServicoSIS/SalvarAtualizarTipoPagamentoResponse")]
        SISClient.ServicoSISReference.TipoPagamentoDTO SalvarAtualizarTipoPagamento(SISClient.ServicoSISReference.TipoPagamentoDTO tipoPagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectTipoPagamento", ReplyAction="http://tempuri.org/IServicoSIS/SelectTipoPagamentoResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.TipoPagamentoDTO> SelectTipoPagamento(SISClient.ServicoSISReference.TipoPagamentoDTO tipoPagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectTipoPagamentoPagina", ReplyAction="http://tempuri.org/IServicoSIS/SelectTipoPagamentoPaginaResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.TipoPagamentoDTO> SelectTipoPagamentoPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.TipoPagamentoDTO tipoPagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/DeleteLocalVenda", ReplyAction="http://tempuri.org/IServicoSIS/DeleteLocalVendaResponse")]
        int DeleteLocalVenda(SISClient.ServicoSISReference.LocalVendaDTO localVenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SalvarAtualizarLocalVenda", ReplyAction="http://tempuri.org/IServicoSIS/SalvarAtualizarLocalVendaResponse")]
        SISClient.ServicoSISReference.LocalVendaDTO SalvarAtualizarLocalVenda(SISClient.ServicoSISReference.LocalVendaDTO localVenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectLocalVenda", ReplyAction="http://tempuri.org/IServicoSIS/SelectLocalVendaResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.LocalVendaDTO> SelectLocalVenda(SISClient.ServicoSISReference.LocalVendaDTO localVenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectLocalVendaPagina", ReplyAction="http://tempuri.org/IServicoSIS/SelectLocalVendaPaginaResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.LocalVendaDTO> SelectLocalVendaPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.LocalVendaDTO localVenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/DeleteFuncionario", ReplyAction="http://tempuri.org/IServicoSIS/DeleteFuncionarioResponse")]
        int DeleteFuncionario(SISClient.ServicoSISReference.FuncionarioDTO funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SalvarAtualizarFuncionario", ReplyAction="http://tempuri.org/IServicoSIS/SalvarAtualizarFuncionarioResponse")]
        SISClient.ServicoSISReference.FuncionarioDTO SalvarAtualizarFuncionario(SISClient.ServicoSISReference.FuncionarioDTO funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectFuncionario", ReplyAction="http://tempuri.org/IServicoSIS/SelectFuncionarioResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.FuncionarioDTO> SelectFuncionario(SISClient.ServicoSISReference.FuncionarioDTO funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectFuncionarioPagina", ReplyAction="http://tempuri.org/IServicoSIS/SelectFuncionarioPaginaResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.FuncionarioDTO> SelectFuncionarioPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.FuncionarioDTO funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/DeleteProduto", ReplyAction="http://tempuri.org/IServicoSIS/DeleteProdutoResponse")]
        int DeleteProduto(SISClient.ServicoSISReference.ProdutoDTO produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SalvarAtualizarProduto", ReplyAction="http://tempuri.org/IServicoSIS/SalvarAtualizarProdutoResponse")]
        SISClient.ServicoSISReference.ProdutoDTO SalvarAtualizarProduto(SISClient.ServicoSISReference.ProdutoDTO produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectProduto", ReplyAction="http://tempuri.org/IServicoSIS/SelectProdutoResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.ProdutoDTO> SelectProduto(SISClient.ServicoSISReference.ProdutoDTO produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoSIS/SelectProdutoPagina", ReplyAction="http://tempuri.org/IServicoSIS/SelectProdutoPaginaResponse")]
        System.Collections.Generic.List<SISClient.ServicoSISReference.ProdutoDTO> SelectProdutoPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.ProdutoDTO produto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoSISChannel : SISClient.ServicoSISReference.IServicoSIS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoSISClient : System.ServiceModel.ClientBase<SISClient.ServicoSISReference.IServicoSIS>, SISClient.ServicoSISReference.IServicoSIS {
        
        public ServicoSISClient() {
        }
        
        public ServicoSISClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoSISClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoSISClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoSISClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DeleteVendedor(SISClient.ServicoSISReference.VendedorDTO vendedor) {
            return base.Channel.DeleteVendedor(vendedor);
        }
        
        public SISClient.ServicoSISReference.VendedorDTO SalvarAtualizarVendedor(SISClient.ServicoSISReference.VendedorDTO vendedor) {
            return base.Channel.SalvarAtualizarVendedor(vendedor);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.VendedorDTO> SelectVendedor(SISClient.ServicoSISReference.VendedorDTO vendedor) {
            return base.Channel.SelectVendedor(vendedor);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.VendedorDTO> SelectVendedorPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.VendedorDTO vendedor) {
            return base.Channel.SelectVendedorPagina(primeiroResultado, quantidadeResultados, vendedor);
        }
        
        public SISClient.ServicoSISReference.UsuarioDTO SelectUsuario(string login, string senha) {
            return base.Channel.SelectUsuario(login, senha);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.ViewControleAcessoDTO> SelectControleAcesso(SISClient.ServicoSISReference.ViewControleAcessoDTO viewControleAcesso) {
            return base.Channel.SelectControleAcesso(viewControleAcesso);
        }
        
        public int DeleteCargo(SISClient.ServicoSISReference.CargoDTO cargo) {
            return base.Channel.DeleteCargo(cargo);
        }
        
        public SISClient.ServicoSISReference.CargoDTO SalvarAtualizarCargo(SISClient.ServicoSISReference.CargoDTO cargo) {
            return base.Channel.SalvarAtualizarCargo(cargo);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.CargoDTO> SelectCargo(SISClient.ServicoSISReference.CargoDTO cargo) {
            return base.Channel.SelectCargo(cargo);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.CargoDTO> SelectCargoPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.CargoDTO cargo) {
            return base.Channel.SelectCargoPagina(primeiroResultado, quantidadeResultados, cargo);
        }
        
        public int DeleteSituacaoVendedor(SISClient.ServicoSISReference.SituacaoVendedorDTO situacaoVendedor) {
            return base.Channel.DeleteSituacaoVendedor(situacaoVendedor);
        }
        
        public SISClient.ServicoSISReference.SituacaoVendedorDTO SalvarAtualizarSituacaoVendedor(SISClient.ServicoSISReference.SituacaoVendedorDTO situacaoVendedor) {
            return base.Channel.SalvarAtualizarSituacaoVendedor(situacaoVendedor);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.SituacaoVendedorDTO> SelectSituacaoVendedor(SISClient.ServicoSISReference.SituacaoVendedorDTO situacaoVendedor) {
            return base.Channel.SelectSituacaoVendedor(situacaoVendedor);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.SituacaoVendedorDTO> SelectSituacaoVendedorPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.SituacaoVendedorDTO situacaoVendedor) {
            return base.Channel.SelectSituacaoVendedorPagina(primeiroResultado, quantidadeResultados, situacaoVendedor);
        }
        
        public int DeleteCategoriaProduto(SISClient.ServicoSISReference.CategoriaProdutoDTO categoriaProduto) {
            return base.Channel.DeleteCategoriaProduto(categoriaProduto);
        }
        
        public SISClient.ServicoSISReference.CategoriaProdutoDTO SalvarAtualizarCategoriaProduto(SISClient.ServicoSISReference.CategoriaProdutoDTO categoriaProduto) {
            return base.Channel.SalvarAtualizarCategoriaProduto(categoriaProduto);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.CategoriaProdutoDTO> SelectCategoriaProduto(SISClient.ServicoSISReference.CategoriaProdutoDTO categoriaProduto) {
            return base.Channel.SelectCategoriaProduto(categoriaProduto);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.CategoriaProdutoDTO> SelectCategoriaProdutoPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.CategoriaProdutoDTO categoriaProduto) {
            return base.Channel.SelectCategoriaProdutoPagina(primeiroResultado, quantidadeResultados, categoriaProduto);
        }
        
        public int DeleteTipoPagamento(SISClient.ServicoSISReference.TipoPagamentoDTO tipoPagamento) {
            return base.Channel.DeleteTipoPagamento(tipoPagamento);
        }
        
        public SISClient.ServicoSISReference.TipoPagamentoDTO SalvarAtualizarTipoPagamento(SISClient.ServicoSISReference.TipoPagamentoDTO tipoPagamento) {
            return base.Channel.SalvarAtualizarTipoPagamento(tipoPagamento);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.TipoPagamentoDTO> SelectTipoPagamento(SISClient.ServicoSISReference.TipoPagamentoDTO tipoPagamento) {
            return base.Channel.SelectTipoPagamento(tipoPagamento);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.TipoPagamentoDTO> SelectTipoPagamentoPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.TipoPagamentoDTO tipoPagamento) {
            return base.Channel.SelectTipoPagamentoPagina(primeiroResultado, quantidadeResultados, tipoPagamento);
        }
        
        public int DeleteLocalVenda(SISClient.ServicoSISReference.LocalVendaDTO localVenda) {
            return base.Channel.DeleteLocalVenda(localVenda);
        }
        
        public SISClient.ServicoSISReference.LocalVendaDTO SalvarAtualizarLocalVenda(SISClient.ServicoSISReference.LocalVendaDTO localVenda) {
            return base.Channel.SalvarAtualizarLocalVenda(localVenda);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.LocalVendaDTO> SelectLocalVenda(SISClient.ServicoSISReference.LocalVendaDTO localVenda) {
            return base.Channel.SelectLocalVenda(localVenda);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.LocalVendaDTO> SelectLocalVendaPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.LocalVendaDTO localVenda) {
            return base.Channel.SelectLocalVendaPagina(primeiroResultado, quantidadeResultados, localVenda);
        }
        
        public int DeleteFuncionario(SISClient.ServicoSISReference.FuncionarioDTO funcionario) {
            return base.Channel.DeleteFuncionario(funcionario);
        }
        
        public SISClient.ServicoSISReference.FuncionarioDTO SalvarAtualizarFuncionario(SISClient.ServicoSISReference.FuncionarioDTO funcionario) {
            return base.Channel.SalvarAtualizarFuncionario(funcionario);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.FuncionarioDTO> SelectFuncionario(SISClient.ServicoSISReference.FuncionarioDTO funcionario) {
            return base.Channel.SelectFuncionario(funcionario);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.FuncionarioDTO> SelectFuncionarioPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.FuncionarioDTO funcionario) {
            return base.Channel.SelectFuncionarioPagina(primeiroResultado, quantidadeResultados, funcionario);
        }
        
        public int DeleteProduto(SISClient.ServicoSISReference.ProdutoDTO produto) {
            return base.Channel.DeleteProduto(produto);
        }
        
        public SISClient.ServicoSISReference.ProdutoDTO SalvarAtualizarProduto(SISClient.ServicoSISReference.ProdutoDTO produto) {
            return base.Channel.SalvarAtualizarProduto(produto);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.ProdutoDTO> SelectProduto(SISClient.ServicoSISReference.ProdutoDTO produto) {
            return base.Channel.SelectProduto(produto);
        }
        
        public System.Collections.Generic.List<SISClient.ServicoSISReference.ProdutoDTO> SelectProdutoPagina(int primeiroResultado, int quantidadeResultados, SISClient.ServicoSISReference.ProdutoDTO produto) {
            return base.Channel.SelectProdutoPagina(primeiroResultado, quantidadeResultados, produto);
        }
    }
}
