//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConciliacaoClient.ConciliacaoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtratoContaBancoDTO", Namespace="http://schemas.datacontract.org/2004/07/ConciliacaoService.Model")]
    [System.SerializableAttribute()]
    public partial class ExtratoContaBancoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string anoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string conciliadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataBalanceteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dataMovimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string historicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idContaCaixaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ano {
            get {
                return this.anoField;
            }
            set {
                if ((object.ReferenceEquals(this.anoField, value) != true)) {
                    this.anoField = value;
                    this.RaisePropertyChanged("ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string conciliado {
            get {
                return this.conciliadoField;
            }
            set {
                if ((object.ReferenceEquals(this.conciliadoField, value) != true)) {
                    this.conciliadoField = value;
                    this.RaisePropertyChanged("conciliado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataBalancete {
            get {
                return this.dataBalanceteField;
            }
            set {
                if ((this.dataBalanceteField.Equals(value) != true)) {
                    this.dataBalanceteField = value;
                    this.RaisePropertyChanged("dataBalancete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dataMovimento {
            get {
                return this.dataMovimentoField;
            }
            set {
                if ((this.dataMovimentoField.Equals(value) != true)) {
                    this.dataMovimentoField = value;
                    this.RaisePropertyChanged("dataMovimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.documentoField, value) != true)) {
                    this.documentoField = value;
                    this.RaisePropertyChanged("documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string historico {
            get {
                return this.historicoField;
            }
            set {
                if ((object.ReferenceEquals(this.historicoField, value) != true)) {
                    this.historicoField = value;
                    this.RaisePropertyChanged("historico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idContaCaixa {
            get {
                return this.idContaCaixaField;
            }
            set {
                if ((this.idContaCaixaField.Equals(value) != true)) {
                    this.idContaCaixaField = value;
                    this.RaisePropertyChanged("idContaCaixa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mes {
            get {
                return this.mesField;
            }
            set {
                if ((object.ReferenceEquals(this.mesField, value) != true)) {
                    this.mesField = value;
                    this.RaisePropertyChanged("mes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observacao {
            get {
                return this.observacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.observacaoField, value) != true)) {
                    this.observacaoField = value;
                    this.RaisePropertyChanged("observacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valor {
            get {
                return this.valorField;
            }
            set {
                if ((this.valorField.Equals(value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContaCaixaDTO", Namespace="http://schemas.datacontract.org/2004/07/ConciliacaoService.Model")]
    [System.SerializableAttribute()]
    public partial class ContaCaixaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string digitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idAgenciaBancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<char> tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string digito {
            get {
                return this.digitoField;
            }
            set {
                if ((object.ReferenceEquals(this.digitoField, value) != true)) {
                    this.digitoField = value;
                    this.RaisePropertyChanged("digito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idAgenciaBanco {
            get {
                return this.idAgenciaBancoField;
            }
            set {
                if ((this.idAgenciaBancoField.Equals(value) != true)) {
                    this.idAgenciaBancoField = value;
                    this.RaisePropertyChanged("idAgenciaBanco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<char> tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((this.tipoField.Equals(value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDTO", Namespace="http://schemas.datacontract.org/2004/07/ConciliacaoService.Model")]
    [System.SerializableAttribute()]
    public partial class UsuarioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdColaboradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPapelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Administrador {
            get {
                return this.AdministradorField;
            }
            set {
                if ((object.ReferenceEquals(this.AdministradorField, value) != true)) {
                    this.AdministradorField = value;
                    this.RaisePropertyChanged("Administrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdColaborador {
            get {
                return this.IdColaboradorField;
            }
            set {
                if ((this.IdColaboradorField.Equals(value) != true)) {
                    this.IdColaboradorField = value;
                    this.RaisePropertyChanged("IdColaborador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPapel {
            get {
                return this.IdPapelField;
            }
            set {
                if ((this.IdPapelField.Equals(value) != true)) {
                    this.IdPapelField = value;
                    this.RaisePropertyChanged("IdPapel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewControleAcessoDTO", Namespace="http://schemas.datacontract.org/2004/07/ConciliacaoService.Model")]
    [System.SerializableAttribute()]
    public partial class ViewControleAcessoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormularioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPapelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formulario {
            get {
                return this.FormularioField;
            }
            set {
                if ((object.ReferenceEquals(this.FormularioField, value) != true)) {
                    this.FormularioField = value;
                    this.RaisePropertyChanged("Formulario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((object.ReferenceEquals(this.HabilitadoField, value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncao {
            get {
                return this.IdFuncaoField;
            }
            set {
                if ((this.IdFuncaoField.Equals(value) != true)) {
                    this.IdFuncaoField = value;
                    this.RaisePropertyChanged("IdFuncao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPapel {
            get {
                return this.IdPapelField;
            }
            set {
                if ((this.IdPapelField.Equals(value) != true)) {
                    this.IdPapelField = value;
                    this.RaisePropertyChanged("IdPapel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaDTO", Namespace="http://schemas.datacontract.org/2004/07/ConciliacaoService.Model")]
    [System.SerializableAttribute()]
    public partial class EmpresaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliquotaCofinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliquotaPisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliquotaSatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnpjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoGpsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoIbgeCidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoIbgeUfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTerceirosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInicioAtividadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInscJuntaComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagemLogotipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoEstadualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoEstadualStField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoJuntaComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoMunicipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeFantasiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazaoSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuframaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoRegimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliquotaCofins {
            get {
                return this.AliquotaCofinsField;
            }
            set {
                if ((object.ReferenceEquals(this.AliquotaCofinsField, value) != true)) {
                    this.AliquotaCofinsField = value;
                    this.RaisePropertyChanged("AliquotaCofins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliquotaPis {
            get {
                return this.AliquotaPisField;
            }
            set {
                if ((object.ReferenceEquals(this.AliquotaPisField, value) != true)) {
                    this.AliquotaPisField = value;
                    this.RaisePropertyChanged("AliquotaPis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliquotaSat {
            get {
                return this.AliquotaSatField;
            }
            set {
                if ((object.ReferenceEquals(this.AliquotaSatField, value) != true)) {
                    this.AliquotaSatField = value;
                    this.RaisePropertyChanged("AliquotaSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cnpj {
            get {
                return this.CnpjField;
            }
            set {
                if ((object.ReferenceEquals(this.CnpjField, value) != true)) {
                    this.CnpjField = value;
                    this.RaisePropertyChanged("Cnpj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoGps {
            get {
                return this.CodigoGpsField;
            }
            set {
                if ((this.CodigoGpsField.Equals(value) != true)) {
                    this.CodigoGpsField = value;
                    this.RaisePropertyChanged("CodigoGps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoIbgeCidade {
            get {
                return this.CodigoIbgeCidadeField;
            }
            set {
                if ((this.CodigoIbgeCidadeField.Equals(value) != true)) {
                    this.CodigoIbgeCidadeField = value;
                    this.RaisePropertyChanged("CodigoIbgeCidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoIbgeUf {
            get {
                return this.CodigoIbgeUfField;
            }
            set {
                if ((this.CodigoIbgeUfField.Equals(value) != true)) {
                    this.CodigoIbgeUfField = value;
                    this.RaisePropertyChanged("CodigoIbgeUf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTerceiros {
            get {
                return this.CodigoTerceirosField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTerceirosField, value) != true)) {
                    this.CodigoTerceirosField = value;
                    this.RaisePropertyChanged("CodigoTerceiros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contato {
            get {
                return this.ContatoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContatoField, value) != true)) {
                    this.ContatoField = value;
                    this.RaisePropertyChanged("Contato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Crt {
            get {
                return this.CrtField;
            }
            set {
                if ((object.ReferenceEquals(this.CrtField, value) != true)) {
                    this.CrtField = value;
                    this.RaisePropertyChanged("Crt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInicioAtividades {
            get {
                return this.DataInicioAtividadesField;
            }
            set {
                if ((this.DataInicioAtividadesField.Equals(value) != true)) {
                    this.DataInicioAtividadesField = value;
                    this.RaisePropertyChanged("DataInicioAtividades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInscJuntaComercial {
            get {
                return this.DataInscJuntaComercialField;
            }
            set {
                if ((this.DataInscJuntaComercialField.Equals(value) != true)) {
                    this.DataInscJuntaComercialField = value;
                    this.RaisePropertyChanged("DataInscJuntaComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagemLogotipo {
            get {
                return this.ImagemLogotipoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemLogotipoField, value) != true)) {
                    this.ImagemLogotipoField = value;
                    this.RaisePropertyChanged("ImagemLogotipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoEstadual {
            get {
                return this.InscricaoEstadualField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoEstadualField, value) != true)) {
                    this.InscricaoEstadualField = value;
                    this.RaisePropertyChanged("InscricaoEstadual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoEstadualSt {
            get {
                return this.InscricaoEstadualStField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoEstadualStField, value) != true)) {
                    this.InscricaoEstadualStField = value;
                    this.RaisePropertyChanged("InscricaoEstadualSt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoJuntaComercial {
            get {
                return this.InscricaoJuntaComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoJuntaComercialField, value) != true)) {
                    this.InscricaoJuntaComercialField = value;
                    this.RaisePropertyChanged("InscricaoJuntaComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoMunicipal {
            get {
                return this.InscricaoMunicipalField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoMunicipalField, value) != true)) {
                    this.InscricaoMunicipalField = value;
                    this.RaisePropertyChanged("InscricaoMunicipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeFantasia {
            get {
                return this.NomeFantasiaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeFantasiaField, value) != true)) {
                    this.NomeFantasiaField = value;
                    this.RaisePropertyChanged("NomeFantasia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazaoSocial {
            get {
                return this.RazaoSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazaoSocialField, value) != true)) {
                    this.RazaoSocialField = value;
                    this.RaisePropertyChanged("RazaoSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suframa {
            get {
                return this.SuframaField;
            }
            set {
                if ((object.ReferenceEquals(this.SuframaField, value) != true)) {
                    this.SuframaField = value;
                    this.RaisePropertyChanged("Suframa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoRegime {
            get {
                return this.TipoRegimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoRegimeField, value) != true)) {
                    this.TipoRegimeField = value;
                    this.RaisePropertyChanged("TipoRegime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConciliacaoService.IConciliacaoService")]
    public interface IConciliacaoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConciliacaoService/selectExtrato", ReplyAction="http://tempuri.org/IConciliacaoService/selectExtratoResponse")]
        System.Collections.Generic.List<ConciliacaoClient.ConciliacaoService.ExtratoContaBancoDTO> selectExtrato(ConciliacaoClient.ConciliacaoService.ExtratoContaBancoDTO extrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConciliacaoService/saveUpdateListaExtrato", ReplyAction="http://tempuri.org/IConciliacaoService/saveUpdateListaExtratoResponse")]
        int saveUpdateListaExtrato(System.Collections.Generic.List<ConciliacaoClient.ConciliacaoService.ExtratoContaBancoDTO> listaExtrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConciliacaoService/conciliarCheques", ReplyAction="http://tempuri.org/IConciliacaoService/conciliarChequesResponse")]
        int conciliarCheques(ConciliacaoClient.ConciliacaoService.ExtratoContaBancoDTO extrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConciliacaoService/conciliarLancamentos", ReplyAction="http://tempuri.org/IConciliacaoService/conciliarLancamentosResponse")]
        int conciliarLancamentos(ConciliacaoClient.ConciliacaoService.ExtratoContaBancoDTO extrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConciliacaoService/selectContaCaixa", ReplyAction="http://tempuri.org/IConciliacaoService/selectContaCaixaResponse")]
        System.Collections.Generic.List<ConciliacaoClient.ConciliacaoService.ContaCaixaDTO> selectContaCaixa(ConciliacaoClient.ConciliacaoService.ContaCaixaDTO contaCaixa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConciliacaoService/selectUsuario", ReplyAction="http://tempuri.org/IConciliacaoService/selectUsuarioResponse")]
        ConciliacaoClient.ConciliacaoService.UsuarioDTO selectUsuario(string login, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConciliacaoService/selectControleAcesso", ReplyAction="http://tempuri.org/IConciliacaoService/selectControleAcessoResponse")]
        System.Collections.Generic.List<ConciliacaoClient.ConciliacaoService.ViewControleAcessoDTO> selectControleAcesso(ConciliacaoClient.ConciliacaoService.ViewControleAcessoDTO viewControleAcesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConciliacaoService/selectEmpresa", ReplyAction="http://tempuri.org/IConciliacaoService/selectEmpresaResponse")]
        System.Collections.Generic.List<ConciliacaoClient.ConciliacaoService.EmpresaDTO> selectEmpresa(ConciliacaoClient.ConciliacaoService.EmpresaDTO empresa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConciliacaoServiceChannel : ConciliacaoClient.ConciliacaoService.IConciliacaoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConciliacaoServiceClient : System.ServiceModel.ClientBase<ConciliacaoClient.ConciliacaoService.IConciliacaoService>, ConciliacaoClient.ConciliacaoService.IConciliacaoService {
        
        public ConciliacaoServiceClient() {
        }
        
        public ConciliacaoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConciliacaoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConciliacaoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConciliacaoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ConciliacaoClient.ConciliacaoService.ExtratoContaBancoDTO> selectExtrato(ConciliacaoClient.ConciliacaoService.ExtratoContaBancoDTO extrato) {
            return base.Channel.selectExtrato(extrato);
        }
        
        public int saveUpdateListaExtrato(System.Collections.Generic.List<ConciliacaoClient.ConciliacaoService.ExtratoContaBancoDTO> listaExtrato) {
            return base.Channel.saveUpdateListaExtrato(listaExtrato);
        }
        
        public int conciliarCheques(ConciliacaoClient.ConciliacaoService.ExtratoContaBancoDTO extrato) {
            return base.Channel.conciliarCheques(extrato);
        }
        
        public int conciliarLancamentos(ConciliacaoClient.ConciliacaoService.ExtratoContaBancoDTO extrato) {
            return base.Channel.conciliarLancamentos(extrato);
        }
        
        public System.Collections.Generic.List<ConciliacaoClient.ConciliacaoService.ContaCaixaDTO> selectContaCaixa(ConciliacaoClient.ConciliacaoService.ContaCaixaDTO contaCaixa) {
            return base.Channel.selectContaCaixa(contaCaixa);
        }
        
        public ConciliacaoClient.ConciliacaoService.UsuarioDTO selectUsuario(string login, string senha) {
            return base.Channel.selectUsuario(login, senha);
        }
        
        public System.Collections.Generic.List<ConciliacaoClient.ConciliacaoService.ViewControleAcessoDTO> selectControleAcesso(ConciliacaoClient.ConciliacaoService.ViewControleAcessoDTO viewControleAcesso) {
            return base.Channel.selectControleAcesso(viewControleAcesso);
        }
        
        public System.Collections.Generic.List<ConciliacaoClient.ConciliacaoService.EmpresaDTO> selectEmpresa(ConciliacaoClient.ConciliacaoService.EmpresaDTO empresa) {
            return base.Channel.selectEmpresa(empresa);
        }
    }
}
